import {ERIS_PHYSICS,type ErisChoices,type ErisSystemState} from '../data/erisSystem';
import {publicAsset} from '../data/publicAsset';
import type {MacroTimeControls} from './CometPanel';
export function ErisSystemPanel({state,choices,enabled,active,status,error,onRetry,onLocate,onSelect,onChange,onStages,time}:{state:ErisSystemState;choices:ErisChoices;enabled:boolean;active:boolean;status:string;error:string;onRetry:()=>void;onLocate:()=>void;onSelect:(id:'eris'|'dysnomia')=>void;onChange:(key:'moon'|'distance')=>void;onStages:()=>void;time:MacroTimeControls}){
 return <section className="small-body-rings" data-eris-system aria-label="阋神星与阋卫一"><small>R03 · 另一矮行星家族</small><h3>阋神星与阋卫一</h3><p>阋卫一 Dysnomia 围绕阋神星运行。两者的位置来自同一套 JPL 卫星解，与主全景共用观测日期。</p>
 <button disabled={enabled&&!state} onClick={enabled?onLocate:onStages}>{enabled?'定位阋神星卫星系统':'开启阶段 03 / 04'}</button><p role="status">{status}</p>{error&&<><p role="alert">{error}</p><button onClick={onRetry}>重试阋神星家族历表</button></>}
 <fieldset disabled={!enabled}><legend>主全景显示</legend><label><input type="checkbox" checked={choices.moon} onChange={()=>onChange('moon')}/>显示阋卫一</label><label><input type="checkbox" checked={choices.distance} onChange={()=>onChange('distance')}/>显示中心距离连线</label></fieldset>
 {active&&state&&<><div className="panorama-moon-list"><button aria-pressed={choices.selected==='eris'} onClick={()=>onSelect('eris')}>阋神星</button><button aria-pressed={choices.selected==='dysnomia'} disabled={!choices.moon} onClick={()=>onSelect('dysnomia')}>阋卫一 · Dysnomia</button></div><dl className="panorama-moon-parameters"><div><dt>两者中心距离</dt><dd>{state.separationKm.toLocaleString('zh-CN',{maximumFractionDigits:1})} km</dd></div><div><dt>卫星相对母星速度</dt><dd>{state.speedKmS.toFixed(4)} km/s</dd></div><div><dt>选中本体参考半径</dt><dd>{ERIS_PHYSICS.radiusKm[choices.selected]} ± {ERIS_PHYSICS.radiusUncertaintyKm[choices.selected]} km</dd></div><div><dt>卫星参考公转周期</dt><dd>{ERIS_PHYSICS.periodDays} 天</dd></div></dl><div className="panorama-family-links"><button disabled={time.loading||state.time<=time.start} onClick={()=>time.onSeek(Math.max(time.start,state.time-86400))}>前 1 天</button><button disabled={time.loading||state.time>=time.end} onClick={()=>time.onSeek(Math.min(time.end,state.time+86400))}>后 1 天</button><button disabled={time.loading} onClick={time.onToggle}>{time.playing?'暂停日期':'继续日期'}</button></div></>}
 <p className="small-ring-scale">两球参考半径与相对间距使用同一局部比例；系统在全景中整体放大。连线只量中心距离，不是轨道、绳索或物质。本批未绘制卫星轨道预测线。</p>
 <details open={active}><summary>真实数据、误差与显示边界</summary><p>使用 2022 年发布的 tnosat_v001 卫星解。本体编号 920136199，卫星编号 120136199；原 136199 小天体编号是系统质心，本页不把它混作母星中心。</p><p>JPL 原始说明给出 2025-01-01 卫星相对母星位置不确定性约 110 km；这不是当前日期的误差上界。插值检查差异小于 1 km，也不代表实际测轨达到这个精度。</p><p>球体、颜色为参考外观，未复原真实自转或精确形状；没有增加质心标记或向引力模型重复计入质量。周期是文献参考值，位置按历表计算。</p><a href={publicAsset('/data/eris-system/manifest.json')} target="_blank" rel="noreferrer">JPL 查询、版本与插值检查 ↗</a><a href={publicAsset('/data/eris-system/physical.json')} target="_blank" rel="noreferrer">参考参数、来源年代与限制 ↗</a><a href={ERIS_PHYSICS.periodSource} target="_blank" rel="noreferrer">NASA 论文存档：阋卫一轨道研究 ↗</a></details></section>;
}
