import { regionMemberById } from '../data/regionMembers';
import { useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, ArrowUpRight, BookOpen, ChevronRight, Compass, Info, Search, X } from 'lucide-react';
import { ATLAS_BODIES, SOLAR_LESSONS, type AtlasBody } from '../data/atlas';
import { bodyById } from '../data/catalog';
import { dynamicDwarfById, isDwarfId, type DwarfId } from '../data/dwarfs';
import { SATELLITES, satelliteById } from '../data/satellites';
import type { BodyId, CameraView } from '../types';
import { AtlasPreview } from './AtlasPreview';
import './ExplorationGuide.css';

export interface ObservationTour {
  id: string; title: string; eyebrow: string; description: string;
  bodyId: BodyId; view: CameraView; speed: number; playing: boolean; satelliteParentId?: BodyId;
}

const OBSERVATION_TOURS: ObservationTour[] = [
  { id: 'home', title: '从地球的一天开始', eyebrow: '01 / OUR HOME', description: '沿着昼夜分界线观察球体的立体形状。把一小时压缩为一秒，看海洋、陆地和云层转过眼前。', bodyId: 'earth', view: 'follow', speed: 3600, playing: true },
  { id: 'star', title: '唯一的恒星', eyebrow: '02 / THE SUN', description: '认识太阳的球体尺度与发光表面。它的直径约为地球的 109 倍，近景会调整镜头距离，方便看清每个天体。', bodyId: 'sun', view: 'follow', speed: 3600, playing: true },
  { id: 'giant', title: '木星，巨大的快旋者', eyebrow: '03 / JUPITER', description: '观看气态巨行星的云带。木星很大，自转却不到 10 小时；一小时每秒的倍率让这种差异直接可见。', bodyId: 'jupiter', view: 'follow', speed: 3600, playing: true },
  { id: 'rings', title: '绕到土星环的另一侧', eyebrow: '04 / SATURN', description: '拖动视角，观察环的倾斜、宽度和薄片结构。球体、环与光照共同形成一个真正可以环绕的三维对象。', bodyId: 'saturn', view: 'follow', speed: 3600, playing: true },
  { id: 'companions', title: '地球与月球之间', eyebrow: '05 / EARTH & MOON', description: '保留地球与月球的真实半径比，只压缩两者距离。用一天每秒观察月球的运行，也可切换真实比例，感受它们之间的空旷。', bodyId: 'moon', view: 'earth-moon', speed: 86400, playing: true },
  { id: 'motion', title: '行星没有一起转动', eyebrow: '06 / ORBITAL MOTION', description: '水星约 88 天绕日一周，地球约 365 天。空间观测压缩轨道距离，同时保留真实方位与运行节奏，让同一倍率下的运动差异清晰可见。', bodyId: 'mercury', view: 'inner', speed: 86400, playing: true },
  { id: 'jovian-moons', title: '木星身边的小太阳系', eyebrow: '07 / JUPITER’S MOONS', description: '同时观察四颗伽利略卫星。木卫一转得最快，木卫四最慢；真实的相对母星历表展现它们不同的相位、倾角与运行节奏。', bodyId: 'jupiter', view: 'follow', satelliteParentId: 'jupiter', speed: 21600, playing: true },
  { id: 'martian-moons', title: '火星与两个小伙伴', eyebrow: '08 / MARS’S MOONS', description: '火卫一不到 8 小时绕火星一周，火卫二则需要约 30 小时。以一小时每秒观看这两个不规则的小世界绕母星运行。', bodyId: 'mars', view: 'follow', satelliteParentId: 'mars', speed: 3600, playing: true },
  { id: 'saturnian-moons', title: '土星环外，各有各的节奏', eyebrow: '09 / SATURN’S MOONS', description: `同场观察已接入的 ${SATELLITES.filter(body => body.parentId === 'saturn').length} 颗卫星。比较土卫一的快速公转与土卫八更远、更倾斜的轨道；点击卫星，近看大撞击坑、冰面与明暗两面的外观示意。`, bodyId: 'saturn', view: 'follow', satelliteParentId: 'saturn', speed: 21600, playing: true },
];
const categories = [{ value: 'all', label: '全部' }, { value: 'dwarf', label: '矮行星' }, { value: 'moon', label: '主要卫星' }, { value: 'small', label: '小天体' }] as const;
const categoryNames = { dwarf: '矮行星', moon: '天然卫星', small: '小天体' };

export function ExplorationGuide({ tab, initialBodyId, onTabChange, onClose, onObserve, onOpenSatellite, onObserveDwarf, onObserveRegion }: { tab: 'atlas' | 'tours'; initialBodyId?: string; onTabChange: (tab: 'atlas' | 'tours') => void; onClose: () => void; onObserve: (tour: ObservationTour) => void; onOpenSatellite?: (parentId: BodyId) => void; onObserveDwarf?: (id: DwarfId) => void; onObserveRegion?: (id:string)=>void }) {
  const [category, setCategory] = useState<'all' | AtlasBody['category']>('all');
  const [query, setQuery] = useState('');
  const [selectedId, setSelectedId] = useState(initialBodyId ?? ATLAS_BODIES[0]?.id);
  const bodies = useMemo(() => ATLAS_BODIES.filter(body => (category === 'all' || category === body.category) && `${body.name} ${body.englishName} ${body.parent}`.toLowerCase().includes(query.trim().toLowerCase())), [category, query]);
  const selected = ATLAS_BODIES.find(body => body.id === selectedId) ?? ATLAS_BODIES[0];
  const liveSatellite = selected ? satelliteById[selected.id] : undefined;
  const liveDwarf = selected && isDwarfId(selected.id) ? dynamicDwarfById[selected.id] : undefined;
  return <section className="exploration-guide" aria-label="太阳系图鉴与观察导览">
    <header className="guide-header"><div><div className="eyebrow">FIELD GUIDE / SOLAR SYSTEM</div><h1>太阳系，远不止八大行星。</h1><p className="guide-time-note">阅读期间观测时间暂停；返回后恢复原状态。</p></div><button className="guide-return" onClick={onClose}><ArrowLeft size={14}/><span>返回观测</span></button></header>
    <div className="guide-tabs" role="tablist" aria-label="探索内容"><button role="tab" aria-selected={tab === 'atlas'} className={tab === 'atlas' ? 'active' : ''} onClick={() => onTabChange('atlas')}><BookOpen size={15}/>天体图鉴<span>{ATLAS_BODIES.length}</span></button><button role="tab" aria-selected={tab === 'tours'} className={tab === 'tours' ? 'active' : ''} onClick={() => onTabChange('tours')}><Compass size={15}/>观察导览<span>{String(OBSERVATION_TOURS.length).padStart(2, '0')}</span></button><p>从看见形状，到理解尺度与运动。</p></div>
    {tab === 'atlas' ? <div className="atlas-workspace" role="tabpanel">
      <aside className="atlas-catalog" aria-label="图鉴天体目录"><label className="atlas-search"><Search size={14}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="搜索天体或所属系统" aria-label="搜索图鉴天体"/>{query && <button onClick={() => setQuery('')} aria-label="清空搜索"><X size={13}/></button>}</label><div className="atlas-filters" aria-label="天体类别">{categories.map(item => <button key={item.value} className={category === item.value ? 'active' : ''} aria-pressed={category === item.value} onClick={() => setCategory(item.value)}>{item.label}</button>)}</div><div className="atlas-count">{bodies.length} 个天体 <span>KNOWLEDGE & OBSERVATION</span></div><div className="atlas-list">{bodies.map(body => <button key={body.id} className={`atlas-body-button ${selected?.id === body.id ? 'selected' : ''}`} onClick={() => setSelectedId(body.id)} aria-pressed={selected?.id === body.id}><i className={`atlas-mini-orb appearance-${body.appearance}`} style={{ '--atlas-color': body.color } as React.CSSProperties}/><span><strong>{body.name}</strong><small>{body.englishName}</small></span><ChevronRight size={12}/></button>)}{bodies.length === 0 && <div className="atlas-empty"><Search size={22}/><p>没有找到匹配的天体。</p><button onClick={() => { setQuery(''); setCategory('all'); }}>查看全部天体</button></div>}</div><p className="atlas-catalog-note">太阳、八大行星及主要卫星可在观测场景中查看。有历表的卫星、谷神星与冥王星—卡戎可直达动态观测。</p></aside>
      {selected && <><div className="atlas-preview"><div className="atlas-preview-heading"><span className="eyebrow">3D STUDY / {selected.englishName.toUpperCase()}</span><span>外观示意</span></div><AtlasPreview body={selected}/><div className="atlas-preview-caption"><span>拖动旋转 · 滚轮缩放</span><p>每个天体独立取景，画面大小不能用于比较真实尺寸。<br/>表面颜色与形态为说明性重建，非实时观测图像。</p></div></div><article className="atlas-details"><div className="eyebrow">BEYOND THE PLANETS</div><span className="atlas-category-tag">{categoryNames[selected.category]} · {selected.parent}</span><h2>{selected.name}</h2><div className="atlas-english-name">{selected.englishName.toUpperCase()}</div><p className="atlas-description">{selected.description}</p><div className="atlas-radius"><span>参考半径</span><strong>{selected.radiusKm === null ? '见尺度说明' : selected.radiusKm.toLocaleString('zh-CN', { maximumFractionDigits: 2 })}<small>{selected.radiusKm === null ? '' : ' km'}</small></strong>{selected.radiusNote && <p>{selected.radiusNote}</p>}{selected.radiusKm !== null && <p>约为地球半径的 {(selected.radiusKm / bodyById.earth.radiusKm).toLocaleString('zh-CN', { maximumFractionDigits: 4 })} 倍</p>}</div><h3>值得留意</h3><ul className="atlas-features">{selected.features.map(feature => <li key={feature}>{feature}</li>)}</ul><div className="atlas-orbit-note"><Info size={14}/><p>{liveDwarf ? '这里预览说明性外观；该天体已接入 2026—2027 年 JPL 几何位置和速度，可进入动态观测。轨迹是当前状态推算的参考轨道，并非逐点下载的未来历表。' : liveSatellite ? '此处只预览静态外观；该卫星已接入真实相对母星历表，可进入系统观察它的真实公转。' : regionMemberById(selected.id) ? '外观为说明性预览；该成员已在宏观结构接入真实历表，可定位、查看当前参数及所属区域。球体外观不表示精确地形。' : selected.id === '67p' ? '此处展示外观示意；67P 已在宏观页接入真实历表。返回观测后，进入“宏观结构 → 天体与物质 → 彗星”，可查看当日位置与速度。' : '这是一份天体资料图鉴，尚未接入该天体的精确历表。预览只演示三维形态，不表示它当前的位置或真实运动速度。'}</p></div>{regionMemberById(selected.id) && onObserveRegion && <button className="atlas-live-orbit-button" onClick={()=>onObserveRegion(selected.id)}><Compass size={13}/>在所属区域定位{selected.name}<ArrowRight size={13}/></button>}{liveDwarf && onObserveDwarf && <button className="atlas-live-orbit-button" onClick={() => onObserveDwarf(liveDwarf.id)}><Compass size={13}/>进入{liveDwarf.name}真实观测<ArrowRight size={13}/></button>}{liveSatellite && onOpenSatellite && <button className="atlas-live-orbit-button" onClick={() => onOpenSatellite(liveSatellite.parentId)}><Compass size={13}/>进入{bodyById[liveSatellite.parentId].name}卫星系统<ArrowRight size={13}/></button>}<a className="atlas-source" href={selected.sourceUrl} target="_blank" rel="noreferrer">查阅权威来源<ArrowUpRight size={12}/></a></article></>}
    </div> : <div className="tour-workspace" role="tabpanel"><div className="tour-intro"><span className="eyebrow">WAYS TO START EXPLORING</span><h2>选一个问题，开始观察。</h2><p>每一站都会打开对应的真实场景，并设置适合观察的镜头与时间倍率。你可以随时暂停、旋转视角或切换天体。</p></div><div className="observation-tours">{OBSERVATION_TOURS.map(tour => <button key={tour.id} className="observation-tour" onClick={() => onObserve(tour)}><div className="tour-visual" style={{ '--tour-color': bodyById[tour.bodyId].color, '--tour-texture': `url(${bodyById[tour.bodyId].texture})` } as React.CSSProperties}><span className={`tour-sphere tour-${tour.bodyId}`}/><span className="tour-number">{tour.eyebrow.slice(0, 2)}</span></div><div className="tour-card-content"><div className="eyebrow">{tour.eyebrow}</div><h3>{tour.title}</h3><p>{tour.description}</p><span className="tour-start">开始观察 <span>{tour.speed === 3600 ? '1 小时 / 秒' : tour.speed === 21600 ? '6 小时 / 秒' : '1 天 / 秒'}<ArrowRight size={14}/></span></span></div></button>)}</div><div className="guide-reading"><div className="eyebrow">UNDERSTAND WHAT YOU SEE</div><h2>先认识太阳系的几类成员</h2><div className="solar-lessons">{SOLAR_LESSONS.map(lesson => <details key={lesson.id}><summary>{lesson.title}<ChevronRight size={14}/></summary><p>{lesson.content}</p><a href={lesson.sourceUrl} target="_blank" rel="noreferrer">来源资料<ArrowUpRight size={11}/></a></details>)}</div></div></div>}
  </section>;
}
