import report from '../../public/data/events/lunar-2026-03-03.json';
import {lunarShadow,inLunarWindow,LUNAR_REFERENCE_TDB,LUNAR_START,LUNAR_END,eclipseBeijing,LUNAR_ECLIPSE_SOURCE} from '../data/lunarEclipse';
import {publicAsset} from '../data/publicAsset';
import type {StateFrame} from '../types';
export function LunarEclipseReadout({frame,compact=false}:{frame:StateFrame|null;compact?:boolean}){
 const valid=!!frame&&inLunarWindow(frame.time),s=valid?lunarShadow(frame):null;
 const xs=(t:number)=>30+(t-LUNAR_START)/(LUNAR_END-LUNAR_START)*260,ys=(km:number)=>136-km/16000*110;
 return <section className={compact?'spin-orbit-inset':'spin-orbit-readout'} data-lunar-eclipse={compact?'inset':'detail'}><strong>2026-03-03 · 月全食案例</strong><p>月球所在截面的地球影区</p>{s?<><b data-eclipse-stage>{s.stage} · 球形几何判断</b><dl><dt>月心距影轴</dt><dd>{Math.round(s.offsetKm).toLocaleString('zh-CN')} km</dd>{!compact&&<><dt>本影 / 半影半径</dt><dd>{Math.round(s.umbraKm)} / {Math.round(s.penumbraKm)} km</dd><dt>月球半径</dt><dd>{s.moonRadiusKm} km</dd></>}</dl></>:<p role="status">{frame?'日期在本案例 8 小时窗口之外，请选择下方案例时刻。':'正在读取日地月历表…'}</p>}{compact?<small>圈线是影区截面边界，不是实体环。尺寸同一比例；暗化为教学标记。</small>:<><p>外圈为半影边界，内圈为本影边界；月球中心越过边界不等于全月盘已经进入。本影全部包住月球时才是本模型的全食。</p><svg viewBox="0 0 320 166" role="img" aria-label="案例八小时内月心距影轴变化，单位千米"><line x1="30" x2="290" y1="136" y2="136" stroke="#698c98"/><line x1="30" x2="30" y1="26" y2="136" stroke="#698c98"/><text x="2" y="22" fill="#c1d7e0" fontSize="10">km</text>{[0,8000,16000].map(n=><text key={n} x="0" y={ys(n)+4} fill="#a8c8ce" fontSize="8">{n}</text>)}<polyline points={report.curve.map(p=>`${xs(p.time)},${ys(p.offsetKm)}`).join(' ')} fill="none" stroke="#f2cd86" strokeWidth="2"/>{valid&&frame&&<line x1={xs(frame.time)} x2={xs(frame.time)} y1="26" y2="136" stroke="#91dcdf"/>}<text x="30" y="155" fill="#b8cfd5" fontSize="10">−4 小时</text><text x="133" y="155" fill="#b8cfd5" fontSize="10">资料食甚</text><text x="250" y="155" fill="#b8cfd5" fontSize="10">+4 小时</text></svg><small>金线：每 5 分钟的模型轴距；青线：当前时间。这个曲线不是亮度曲线。</small><h4>独立资料与模型对照</h4><dl><dt>NASA 资料食甚 · TT/TD</dt><dd>2026-03-03 11:34:52.1</dd><dt>资料时刻换算北京时间</dt><dd>{eclipseBeijing(LUNAR_REFERENCE_TDB)}</dd><dt>本模型最接近影轴 · 北京时间</dt><dd>{eclipseBeijing(report.model.minimumTdb)}</dd><dt>模型时刻 − 资料时刻</dt><dd data-eclipse-error>+{report.model.deltaSeconds.toFixed(1)} 秒</dd><dt>模型最近影轴处食分 / 资料最大食分</dt><dd>{report.model.magnitude.toFixed(4)} / {report.reference.umbralMagnitude}</dd></dl><p>本影食分是影区覆盖月球直径的几何量，可超过 1，不是遮住面积的百分比。模型与资料用同一时间尺度比较；旧资料中的 UT 使用预计 ΔT，不能直接当成 UTC 或北京时间。</p><p>模型采用球形太阳、地球、月球与未经光行时修正的同刻历表，未加入大气影区扩大、地球扁率、视位置修正或月缘地形。暗化不模拟实际“血月”颜色或亮度；差值记录不用于校准动画。</p><p>没有计算观测地点的月出月落、地平高度或天气，不能据此判断你所在城市是否可见。可在上方切换日食球面案例；卫星遮掩仍待实现。</p><a href={LUNAR_ECLIPSE_SOURCE} target="_blank" rel="noreferrer">NASA 食甚与路径资料 ↗</a> · <a href="https://eclipse.gsfc.nasa.gov/LEcat5/shadow.html" target="_blank" rel="noreferrer">NASA：大气与影区扩大 ↗</a> · <a href={publicAsset('/data/events/lunar-2026-03-03.json')} target="_blank" rel="noreferrer">项目计算报告 ↗</a><small>Eclipse Predictions by Fred Espenak and Jean Meeus (NASA GSFC)</small></>}</section>;
}
