import * as THREE from 'three';
import {PRIMARY_BODIES,type PrimaryId} from '../data/macroPrimary';
import {placeMacroLabels} from './macroLabelLayout';
export function createPrimaryLabels(host:HTMLElement,meshes:Record<PrimaryId,THREE.Mesh>,onSelect:(id:PrimaryId)=>void){
 const overlay=document.createElement('div');overlay.className='macro-world-labels primary-world-labels';host.appendChild(overlay);
 const labels=PRIMARY_BODIES.map(body=>{const button=document.createElement('button');button.type='button';button.className='macro-world-label selectable';button.textContent=body.name;button.style.setProperty('--label-color',body.color);button.setAttribute('aria-label',`定位${body.name}本体`);button.onclick=()=>onSelect(body.id as PrimaryId);const leader=document.createElement('span');leader.className='macro-label-leader';leader.style.background=body.color;overlay.append(leader,button);return {id:body.id as PrimaryId,button,leader};});
 return {clear(){for(const {button,leader} of labels){button.style.visibility='hidden';leader.style.visibility='hidden';}},layout(camera:THREE.PerspectiveCamera,width:number,height:number,visible:boolean,active:PrimaryId|null,regionsOnly=false){
  const candidates=labels.flatMap(({id,button,leader})=>{leader.style.visibility='hidden';button.style.visibility='hidden';button.setAttribute('aria-pressed',String(active===id));const mesh=meshes[id];if(!visible||!mesh.visible||(active&&active!==id)||(regionsOnly&&id!=='sun'))return [];const world=mesh.getWorldPosition(new THREE.Vector3()),p=world.clone().project(camera);if(p.z<-1||p.z>1)return [];
   return [{id,x:(p.x+1)*width/2,y:(1-p.y)*height/2,width:button.offsetWidth,height:button.offsetHeight,radius:mesh.userData.labelRadius*(id==='saturn'?2.5:1)*height/(2*Math.tan(camera.fov*Math.PI/360)*world.distanceTo(camera.position))+6}];
  });
  const rect=host.getBoundingClientRect(),obstacles=[...host.querySelectorAll<HTMLElement>('.macro-world-labels:not(.primary-world-labels) .macro-world-label')].filter(b=>b.style.visibility==='visible').map(b=>{const r=b.getBoundingClientRect();return {x:r.x-rect.x,y:r.y-rect.y,width:r.width,height:r.height};});
  for(const box of placeMacroLabels(candidates,width,height,70,110,obstacles)){const {button:b,leader}=labels.find(l=>l.id===box.id)!;b.style.transform=`translate(${box.x}px,${box.y}px)`;b.style.visibility='visible';const x=Math.max(box.x,Math.min(box.anchorX,box.x+box.width)),y=Math.max(box.y,Math.min(box.anchorY,box.y+box.height));const dx=x-box.anchorX,dy=y-box.anchorY,length=Math.hypot(dx,dy),inset=Math.min(length,candidates.find(c=>c.id===box.id)?.radius??0);leader.style.width=`${length-inset}px`;leader.style.transform=`translate(${box.anchorX+(length?dx/length*inset:0)}px,${box.anchorY+(length?dy/length*inset:0)}px) rotate(${Math.atan2(dy,dx)}rad)`;leader.style.visibility=length-inset>2?'visible':'hidden';}
 },dispose(){overlay.remove();}};
}
