import {MOTION_LESSONS,motionStepSeconds,motionSeek,spinPeriodSeconds,type MotionLesson,type MotionLessonId} from '../data/motionLessons';
import {bodyById,PHYSICAL_SOURCE} from '../data/catalog';
import type {MacroTimeControls} from './CometPanel';
import './EnvironmentJourneyPanel.css';
export function MotionLessonPanel({current,epoch,now,time,enabled,onLesson,onExit}:{current:MotionLesson|null;epoch:number|null;now:number|null;time:MacroTimeControls;enabled:boolean;onLesson:(id:MotionLessonId)=>void;onExit:()=>void}){
 const ready=enabled&&now!==null&&!time.loading&&!time.error;
 const delta=current?motionStepSeconds(current.id):0;
 const move=(seconds:number)=>{if(!ready||now===null)return;const next=motionSeek(now,seconds,time.start,time.end);if(next!==null){if(time.playing)time.onToggle();time.onSeek(next);}};
 const can=(seconds:number)=>ready&&now!==null&&motionSeek(now,seconds,time.start,time.end)!==null;
 const index=MOTION_LESSONS.findIndex(s=>s.id===current?.id);
 return <section className="environment-journey" data-motion-lessons aria-label="自转与公转课程"><h3>运动第一课：自转与公转</h3><p>先看球体自身转动，再拉远看绕日运行，最后对照金星。这里直接改变观测日期，整幅太阳系同步更新。</p><ol>{MOTION_LESSONS.map((s,i)=><li key={s.id}><button disabled={!ready} aria-pressed={s.id===current?.id} onClick={()=>onLesson(s.id)}>{i+1} · {s.name}</button></li>)}</ol>{!ready&&<p role="status">{!enabled?'需开启阶段 01 宏观结构。':time.error?'历表读取失败，请从时间栏重试。':time.loading?'正在读取所选日期历表…':'需要真实太阳系历表。'}</p>}{current&&<><h4>{current.title}</h4><p>{current.text}</p><p className="environment-legend">{current.note}</p><p>本体模型恒星自转周期：{(spinPeriodSeconds(current.body)/3600).toLocaleString('zh-CN',{maximumFractionDigits:3})} 小时；资料公转周期：{bodyById[current.body].orbitalPeriodDays.toLocaleString('zh-CN',{maximumFractionDigits:3})} 日。</p><div className="environment-controls"><button disabled={!can(-delta)} onClick={()=>move(-delta)}>{current.id==='earth-orbit'?'后退 30 天':'后退 ¼ 自转周期'}</button><button disabled={!can(delta)} onClick={()=>move(delta)}>{current.id==='earth-orbit'?'前进 30 天':'前进 ¼ 自转周期'}</button><button disabled={!ready} onClick={time.onToggle}>{time.playing?'暂停观测时间':'继续观测时间'}</button><button disabled={!ready||epoch===null||epoch<time.start||epoch>time.end} onClick={()=>{if(epoch!==null){if(time.playing)time.onToggle();time.onSeek(epoch);}}}>重置本节日期</button></div><p>每次步进 {Math.round(delta/3600*100)/100} 小时；越出内置历表范围时禁用。播放沿用底部倍率，快进自转可能产生采样错觉。退出保留当前日期；需要返回起点时先重置本节日期。</p><div className="environment-controls"><button disabled={!ready||index===0} onClick={()=>onLesson(MOTION_LESSONS[index-1].id)}>上一节运动</button><button disabled={!ready||index===MOTION_LESSONS.length-1} onClick={()=>onLesson(MOTION_LESSONS[index+1].id)}>下一节运动</button></div><button onClick={onExit}>退出运动课并恢复全景</button><p><a href={current.source} target="_blank" rel="noreferrer">NASA 概念解释 ↗</a> · <a href={PHYSICAL_SOURCE} target="_blank" rel="noreferrer">JPL 参数 ↗</a> · <a href="https://naif.jpl.nasa.gov/pub/naif/generic_kernels/pck/pck00011.tpc" target="_blank" rel="noreferrer">NAIF 自转常数 ↗</a></p><small>金色线和粉色标记为教学标注，标记不是地理点。自转使用原有 NAIF 线性角速度与静态极轴近似，绝对经度/姿态不用于测绘；本体周期由该角速度反算，可能与四舍五入的参数表略有差别。</small></>}{!current&&<p>选择课程同步定位；原有「行星运动 · 谁转得快」仍提供所有行星的参数比较。</p>}</section>;
}
