import {PATROCLUS_PHYSICS,type PatroclusChoices,type PatroclusSystemState} from '../data/patroclusSystem';
import {publicAsset} from '../data/publicAsset';
import type {MacroTimeControls} from './CometPanel';
export function PatroclusSystemPanel({state,choices,enabled,active,status,error,onRetry,onLocate,onSelect,onChange,onStages,time}:{state:PatroclusSystemState;choices:PatroclusChoices;enabled:boolean;active:boolean;status:string;error:string;onRetry:()=>void;onLocate:()=>void;onSelect:(id:'patroclus'|'menoetius')=>void;onChange:(key:'moon'|'distance')=>void;onStages:()=>void;time:MacroTimeControls}){
 return <section className="small-body-rings" data-patroclus-system aria-label="帕特罗克洛斯双小行星"><small>R03 · 小天体双体与卫星</small><h3>帕特罗克洛斯双小行星</h3><p>Patroclus 与 Menoetius 是木星 L5 特洛伊群中的一对小天体。整体绕太阳，局部相互绕转；尺寸接近且彼此分离，不是接触双体，也不是木星的卫星。</p>
 <button disabled={enabled&&!state} onClick={enabled?onLocate:onStages}>{enabled?'定位双小行星系统':'开启阶段 03 / 04'}</button><p role="status">{status}</p>{error&&<><p role="alert">{error}</p><button onClick={onRetry}>重试双小行星历表</button></>}
 <fieldset disabled={!enabled}><legend>主全景显示</legend><label><input type="checkbox" checked={choices.moon} onChange={()=>onChange('moon')}/>显示伴星 Menoetius</label><label><input type="checkbox" checked={choices.distance} onChange={()=>onChange('distance')}/>显示中心距离连线</label></fieldset>
 {active&&state&&<><div className="panorama-moon-list"><button aria-pressed={choices.selected==='patroclus'} onClick={()=>onSelect('patroclus')}>主星 · Patroclus</button><button aria-pressed={choices.selected==='menoetius'} disabled={!choices.moon} onClick={()=>onSelect('menoetius')}>伴星 · Menoetius</button></div><dl className="panorama-moon-parameters"><div><dt>两者中心距离</dt><dd>{state.separationKm.toLocaleString('zh-CN',{maximumFractionDigits:2})} km</dd></div><div><dt>伴星相对主星速度</dt><dd>{(state.speedKmS*1000).toFixed(3)} m/s</dd></div><div><dt>选中本体参考半径</dt><dd>{PATROCLUS_PHYSICS.radiusKm[choices.selected]} km</dd></div><div><dt>相互绕转参考周期</dt><dd>约 {PATROCLUS_PHYSICS.periodDaysApprox} 天</dd></div></dl><div className="panorama-family-links"><button disabled={time.loading||state.time<=time.start} onClick={()=>time.onSeek(Math.max(time.start,state.time-21600))}>前 6 小时</button><button disabled={time.loading||state.time>=time.end} onClick={()=>time.onSeek(Math.min(time.end,state.time+21600))}>后 6 小时</button><button disabled={time.loading} onClick={time.onToggle}>{time.playing?'暂停日期':'继续日期'}</button><button disabled={time.loading||state.time>=time.end} onClick={time.onPlay}>加速观看绕转</button></div></>}
 <p className="small-ring-scale">两颗球体半径与相对间距共用局部比例，系统整体放大；主星锚点的日心距离压缩。镜头跟随主星，两体位置均来自历表，主星并非固定在太空中。中心连线是量距辅助，不是轨道或绳索。</p>
 <details open={active}><summary>来源、精度与当前范围</summary><p>本体编号 920000617 与 120000617 使用同一 2023-06-01 的 JPL 卫星解 as_20000617_jpl082_v001_。617 小天体编号是系统质心，本页没有把它当作主星。</p><p>2026—2027 按月读取，每 6 小时发布一个状态，以未参与插值的 3 小时检查点验证。两体相对位置最大插值差异约 34 米；这不是绝对测轨误差，不能据此保证实际位置精度。</p><p>参考半径来自该解的对象说明；颜色与球形为示意，没有精确地形或自转姿态。本批未绘制局部预测轨道或精确系统质心，也不向十体引力模型添加质量。约 4.3 天是文献周期，动画位置由历表决定。</p><a href={publicAsset('/data/patroclus-system/manifest.json')} target="_blank" rel="noreferrer">JPL 查询、月包与相对插值检查 ↗</a><a href={publicAsset('/data/patroclus-system/physical.json')} target="_blank" rel="noreferrer">参考参数与来源记录 ↗</a><a href={PATROCLUS_PHYSICS.introductionSource} target="_blank" rel="noreferrer">NASA：Lucy 与这对双小行星 ↗</a><a href={PATROCLUS_PHYSICS.periodSource} target="_blank" rel="noreferrer">相互轨道研究论文 ↗</a></details>
 </section>;
}
