import { Activity, ArrowUpRight, ChevronDown, ChevronRight, CornerDownRight, Info, Orbit, Play, Sparkles } from 'lucide-react';
import { bodyById } from '../data/catalog';
import { ATLAS_BODIES } from '../data/atlas';
import type { SatelliteDefinition } from '../data/satellites';
import type { BodyId, Vec3 } from '../types';

const number = (value: number, digits = 2) => value.toLocaleString('zh-CN', { maximumFractionDigits: digits, minimumFractionDigits: digits });

export function SatelliteChildren({ parentId, satellites, expanded, selectedId, onOverview, onSelect }: { parentId: BodyId; satellites: SatelliteDefinition[]; expanded: boolean; selectedId: string | null; onOverview: () => void; onSelect: (id: string) => void }) {
  return <div className={`satellite-children ${expanded ? 'expanded' : ''}`}><button className="satellite-branch-toggle" onClick={onOverview} aria-expanded={expanded} title="展示本观测站选定的卫星样本，数量不是该行星的卫星总数"><CornerDownRight size={11}/><span>已接入 {satellites.length} 颗 · 观看公转</span>{expanded ? <ChevronDown size={11}/> : <ChevronRight size={11}/>}</button>{expanded && <div className="satellite-child-list" aria-label={`${bodyById[parentId].name}已接入的卫星`}>{satellites.map(body => <button key={body.id} className={selectedId === body.id ? 'selected' : ''} onClick={() => onSelect(body.id)} aria-pressed={selectedId === body.id}><i style={{ background: body.color }}/><span>{body.name}<small>{body.englishName}</small></span><ChevronRight size={11}/></button>)}</div>}</div>;
}

export function SatelliteInspector({ parentId, satellites, selectedId, selectedState, loading, onSelect, onOverview, onPlay, onLearn }: { parentId: BodyId; satellites: SatelliteDefinition[]; selectedId: string | null; selectedState?: { position: Vec3; velocity: Vec3 }; loading: boolean; onSelect: (id: string) => void; onOverview: () => void; onPlay: () => void; onLearn: () => void }) {
  const parent = bodyById[parentId];
  const systemDescription = parentId === 'uranus'
    ? '天王星的自转轴倾斜约 98°，几乎侧躺着绕太阳运行。这组主要卫星大致沿母星赤道面公转；天卫五的轨道倾角更明显。拖动镜头，可以观察整个家族的倾斜结构。'
    : parentId === 'saturn'
    ? `土星环外是一组运行节奏不同的卫星。本观测站已接入 ${satellites.length} 颗：土卫一不到一天绕行一周，遥远的土卫八则需要约 79 天。土卫八的轨道明显偏离其他主要卫星的共同平面；拖动镜头，可以看清这种倾斜。`
    : `${parent.name}绕太阳运行，同时也是这些卫星的母星。每颗卫星都有自己的轨道周期；以母星为中心观察，可以看清它们不同步的公转。`;
  const selected = satellites.find(body => body.id === selectedId);
  const atlas = selected ? ATLAS_BODIES.find(body => body.id === selected.id) : undefined;
  const duration = (days: number) => days < 2 ? `${number(days * 24, 2)} 小时` : `${number(days, 3)} 天`;
  const distance = selectedState ? Math.hypot(...selectedState.position) : null;
  const velocity = selectedState ? Math.hypot(...selectedState.velocity) : null;
  return <aside className="inspector satellite-inspector" aria-label={selected ? `${selected.name}卫星详情` : `${parent.name}卫星系统详情`}>
    <div className="inspector-header"><div className="eyebrow">{selected ? 'NATURAL SATELLITE' : 'A SYSTEM WITHIN A SYSTEM'}</div><div className="inspector-title-line"><h2>{selected?.name ?? `${parent.name}系统`}</h2><span className="satellite-profile-orb" style={{ backgroundColor: selected?.color ?? parent.color }}/></div><div className="inspector-english">{selected?.englishName.toUpperCase() ?? `${parent.englishName.toUpperCase()} & MOONS`}</div><div className="orbital-hierarchy"><span>太阳</span><ChevronRight size={10}/><strong>{parent.name}</strong><ChevronRight size={10}/><span>{selected?.name ?? `已接入 ${satellites.length} 颗卫星`}</span></div><p className="body-description">{selected?.description ?? systemDescription}</p>{selected ? <button className="follow-button" onClick={onOverview}><Orbit size={13}/>返回{parent.name}系统全景</button> : <button className="follow-button" onClick={onPlay}><Play size={12}/>加速观看卫星公转</button>}</div>
    <div className="knowledge-teaser"><div className="knowledge-teaser-heading"><Orbit size={13}/>卫星运行小课堂</div><p>从太阳、母星到卫星，按层次理解公转关系与轨迹。</p><button onClick={onLearn}>认识卫星与运行方式 <ArrowUpRight size={11}/></button></div>
    {selected ? <>
      <div className="inspector-section"><h3 className="section-label"><Orbit size={13}/>轨道与尺度</h3><dl className="property-grid"><div className="property"><dt>参考平均半径</dt><dd>{number(selected.radiusKm, 1)}<small>km</small></dd></div><div className="property"><dt>绕母星一周</dt><dd className="satellite-period-value">{duration(selected.orbitalPeriodDays)}</dd></div><div className="property"><dt>围绕谁运行</dt><dd>{parent.name}</dd></div><div className="property"><dt>相对母星半径</dt><dd>{number(selected.radiusKm / parent.radiusKm * 100, 2)}<small>%</small></dd></div><div className="property"><dt>标准引力参数 GM</dt><dd className="satellite-period-value">{number(selected.gm, selected.gm < 1 ? 9 : 6)}<small>km³/s²</small></dd></div></dl>{selected.radiusNote && <p className="reference-note">{selected.radiusNote}</p>}</div>
      <div className="inspector-section"><div className="realtime-title"><h3 className="section-label"><Activity size={13}/>此刻的相对状态</h3><span className="live-badge"><i className="status-dot"/>JPL</span></div><div className="state-value"><span>距{parent.name}中心</span><strong>{loading || distance === null ? '—' : number(distance, 0)}<small>km</small></strong></div><div className="state-value"><span>相对{parent.name}速度</span><strong>{loading || velocity === null ? '—' : number(velocity, 3)}<small>km/s</small></strong></div><p className="reference-note">{loading ? '正在同步所选时刻的卫星历表。' : `这些数值是相对${parent.name}中心的真实几何状态，不受画面压缩影响。`}</p></div>
      {atlas?.features[0] && <div className="inspector-section"><p className="body-fact"><Sparkles size={13}/>{atlas.features[0]}</p>{selected.id === 'triton' && <p className="reference-note">海卫一逆向绕海王星公转；逆行方向由真实历表保留。</p>}{selected.id === 'iapetus' && <p className="reference-note">画面用明暗材质与赤道山脊说明表面特征；表面经纬位置与地形细节未复现实测测绘。太阳照明另外决定昼夜。</p>}{['mimas', 'tethys'].includes(selected.id) && <p className="reference-note">近景的大坑与起伏为特征示意，不复原实测经纬位置，也不能用作地形测量。</p>}</div>}
    </> : <div className="inspector-section"><h3 className="section-label"><Orbit size={13}/>它们并不同步</h3><div className="satellite-period-list">{satellites.map(body => <button key={body.id} onClick={() => onSelect(body.id)}><i style={{ background: body.color }}/><span>{body.name}<small>{body.englishName}</small></span><strong>{duration(body.orbitalPeriodDays)}</strong><ChevronRight size={11}/></button>)}</div><p className="reference-note">右侧为绕{parent.name}一周的参考周期。点击卫星进入近景；返回系统全景可同时观察不同运行节奏。</p></div>}
    <div className="inspector-section satellite-boundary"><h3 className="section-label"><Info size={13}/>观测约定</h3><p>这里只展示已接入的选定卫星，不表示母星的卫星总数。位置来自 NASA / JPL 相对母星历表，共用底部时间。空间观测会压缩距离并增强球体可见性；切换真实比例可检查尺度。</p><p>本视图用于真实历表观测；新增卫星不参与十体牛顿引力验证。表面外观为静态资料与示意重建，不是实时影像。</p>{selected && <><a className="source-link" href={selected.sourceUrl} target="_blank" rel="noreferrer">NASA 天体资料<ArrowUpRight size={11}/></a><a className="source-link" href={selected.parameterSourceUrl} target="_blank" rel="noreferrer">NAIF 尺度参数<ArrowUpRight size={11}/></a><a className="source-link" href={selected.orbitalPeriodSourceUrl} target="_blank" rel="noreferrer">公转周期来源<ArrowUpRight size={11}/></a><a className="source-link" href={selected.gmSourceUrl} target="_blank" rel="noreferrer">引力参数来源<ArrowUpRight size={11}/></a></>}{!selected && parentId === 'saturn' && <a className="source-link" href="https://science.nasa.gov/saturn/moons/" target="_blank" rel="noreferrer">NASA 土星卫星资料<ArrowUpRight size={11}/></a>}{!selected && parentId === 'uranus' && <a className="source-link" href="https://science.nasa.gov/uranus/moons/" target="_blank" rel="noreferrer">NASA 天王星卫星资料<ArrowUpRight size={11}/></a>}<a className="source-link" href="https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/satellites/" target="_blank" rel="noreferrer">JPL / NAIF 轨道数据<ArrowUpRight size={11}/></a></div>
  </aside>;
}
