import integrationReport from '../../docs/MAIN-SCENE-INTEGRATION.md?url';
import {MACRO_LAYERS,type MacroLayerId} from '../data/macroLayers';
import {INTEGRATED_ITEMS,type IntegratedId} from '../data/integratedScene';
import {presenceText,type SceneSnapshot} from './scenePresence';
export function SceneInventory({coorbitalStatus,onCoorbital,onEnceladus,enceladusStatus,onErosShape,erosShapeStatus,onPatroclus,patroclusStatus,onEris,erisStatus,onPluto,plutoStatus,smallRingsStatus,onSmallRings,snapshot,onLocate,onPhenomenon,onHistory,status,phenomenonStatus,ringsStatus}:{coorbitalStatus:string;onCoorbital:()=>void;onEnceladus:()=>void;enceladusStatus:string;onErosShape:()=>void;erosShapeStatus:string;onPatroclus:()=>void;patroclusStatus:string;onEris:()=>void;erisStatus:string;onPluto:()=>void;plutoStatus:string;smallRingsStatus:string;onSmallRings:()=>void;snapshot:SceneSnapshot;ringsStatus:string;status:(id:MacroLayerId)=>string;phenomenonStatus:(id:IntegratedId)=>string;onLocate:(id:MacroLayerId|'sun'|'rings')=>void;onPhenomenon:(id:IntegratedId)=>void;onHistory:()=>void}){
 return <section className="scene-inventory" aria-label="实际场景清单"><h2>全景里有什么？</h2><p>状态来自当前三维场景。视野外仍然存在；靠近展开细节。近景会暂隐无关成员，返回全景恢复。</p><p className="scene-inventory-note">“视野内”表示图形与镜头范围相交，小尺寸或遮挡仍可能难以辨认。点云和空间现象是示意，奥尔特云是推断。</p>
 <div className="scene-inventory-row" data-scene-item="sun"><span>太阳本体<small>{presenceText(snapshot,'sun')}</small></span><button onClick={()=>onLocate('sun')}>定位</button></div>
 <div className="scene-inventory-row" data-scene-item="coorbital" data-rendered={snapshot.coorbital?.rendered??0}><span>Kamoʻoalewa · 地球准卫星<small>{coorbitalStatus}</small></span><button onClick={onCoorbital}>定位 / 参照系对照</button></div>
 {MACRO_LAYERS.map(item=><div className="scene-inventory-row" data-scene-item={item.id} data-rendered={snapshot[item.id]?.rendered??0} key={item.id}><span>{item.name}<small>{status(item.id)}</small></span><button onClick={()=>onLocate(item.id)}>定位 / 展开</button></div>)}
 <div className="scene-inventory-row" data-scene-item="rings"><span>四大巨行星环<small>{ringsStatus}</small></span><button onClick={()=>onLocate('rings')}>定位土星环</button></div>
 <div className="scene-inventory-row" data-scene-item="small-rings" data-rendered={snapshot['small-rings']?.rendered??0}><span>女凯龙星双环<small>{smallRingsStatus}</small></span><button onClick={onSmallRings}>定位 / 控制</button></div>
 <div className="scene-inventory-row" data-scene-item="pluto-small-moons" data-rendered={snapshot['pluto-small-moons']?.rendered??0}><span>冥王星五颗卫星<small>{plutoStatus}</small></span><button onClick={onPluto}>定位全家族</button></div>
 <div className="scene-inventory-row" data-scene-item="eris-system" data-rendered={snapshot['eris-system']?.rendered??0}><span>阋神星与阋卫一<small>{erisStatus}</small></span><button onClick={onEris}>定位 / 控制</button></div>
 <div className="scene-inventory-row" data-scene-item="patroclus-system" data-rendered={snapshot['patroclus-system']?.rendered??0}><span>帕特罗克洛斯双小行星<small>{patroclusStatus}</small></span><button onClick={onPatroclus}>定位 / 控制</button></div>
 <div className="scene-inventory-row" data-scene-item="eros-shape" data-rendered={snapshot['eros-shape']?.rendered??0}><span>爱神星不规则形状<small>{erosShapeStatus}</small></span><button onClick={onErosShape}>定位 / 控制</button></div>
 <div className="scene-inventory-row" data-scene-item="enceladus-detail" data-rendered={snapshot['enceladus-detail']?.rendered??0}><span>土卫二喷流与内部结构<small>{enceladusStatus}</small></span><button onClick={onEnceladus}>定位 / 控制</button></div>
 {INTEGRATED_ITEMS.map(item=><div className="scene-inventory-row" data-scene-item={item.id==='dust'?'stream':item.id} data-rendered={snapshot[item.id==='dust'?'stream':item.id]?.rendered??0} key={item.id}><span>{item.title}<small>{phenomenonStatus(item.id)}</small></span><button onClick={()=>onPhenomenon(item.id)}>{item.id==='environment'?'定位地球 / 控制':'定位 / 控制'}</button></div>)}
 <div className="scene-inventory-row" data-scene-item="historical"><span>2I/Borisov<small>历史场景 · 2019—2020</small></span><button onClick={onHistory}>切换历史</button></div>
 <a href={integrationReport} download="主全景整合与验收.md">查看本次整合范围与验收说明 ↗</a><p>背景装饰星点不是实测星空；邻星和星系在顶部的宇宙尺度页解释，不摆进太阳系内部。</p></section>;
}
