import {createSolarFlare} from './solarFlare';
import {useEffect,useRef,useState,type KeyboardEvent} from 'react';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {publicAsset} from '../data/publicAsset';
import {SOLAR_ACTIVITY_LAYERS,SOLAR_ACTIVITY_SOURCES,defaultSolarActivityLayers,solarDemoState,advanceSolarDemo,type SolarActivityLayers} from '../data/solarActivity';
import './SpaceEnvironment.css';
import './SolarActivity.css';
function ActivityCanvas({layers,progress,reset}:{layers:SolarActivityLayers;progress:number;reset:number}){
 const host=useRef<HTMLDivElement>(null),latest=useRef({layers,progress,reset});latest.current={layers,progress,reset};const [error,setError]=useState('');
 useEffect(()=>{
  const element=host.current;if(!element)return;let renderer:THREE.WebGLRenderer;
  try{renderer=new THREE.WebGLRenderer({antialias:true});}catch{setError('当前设备无法显示三维画面，说明和来源仍可阅读。');return;}
  renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.setClearColor('#090f1b');renderer.outputColorSpace=THREE.SRGBColorSpace;element.appendChild(renderer.domElement);
  const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(42,1,.1,150),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=5;controls.maxDistance=65;
  const surface=new THREE.MeshBasicMaterial({color:'#ffb054'}),sun=new THREE.Mesh(new THREE.SphereGeometry(2,80,64),surface);sun.position.x=-5;scene.add(sun);let disposed=false;
  new THREE.TextureLoader().load(publicAsset('/textures/sun.jpg'),texture=>{if(disposed){texture.dispose();return;}texture.colorSpace=THREE.SRGBColorSpace;surface.map=texture;surface.color.set('#ffffff');surface.needsUpdate=true;},undefined,()=>{if(!disposed)setError('太阳纹理未读取，示意球体与活动仍可观察。');});
  const corona=new THREE.Group();corona.position.copy(sun.position);scene.add(corona);
  for(const [radius,opacity] of [[2.08,.32],[2.3,.19],[2.75,.09]]){
   const glow=new THREE.Mesh(new THREE.SphereGeometry(radius,48,32),new THREE.ShaderMaterial({side:THREE.BackSide,transparent:true,depthWrite:false,uniforms:{strength:{value:opacity}},vertexShader:'varying vec3 n;varying vec3 v;void main(){vec4 p=modelViewMatrix*vec4(position,1.);n=normalize(normalMatrix*normal);v=normalize(-p.xyz);gl_Position=projectionMatrix*p;}',fragmentShader:'varying vec3 n;varying vec3 v;uniform float strength;void main(){float a=pow(1.-abs(dot(normalize(n),normalize(v))),2.);gl_FragColor=vec4(1.,.48,.15,a*strength);}'}));corona.add(glow);
  }
  const dotMaterial=(color:string,size:number,opacity:number)=>new THREE.ShaderMaterial({transparent:true,depthWrite:false,uniforms:{color:{value:new THREE.Color(color)},opacity:{value:opacity},size:{value:size}},vertexShader:'uniform float size;void main(){gl_PointSize=size;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'uniform vec3 color;uniform float opacity;void main(){float d=length(gl_PointCoord-.5);if(d>.5)discard;gl_FragColor=vec4(color,opacity*(1.-2.*d));}'});
  const windGeometry=new THREE.BufferGeometry(),windPositions=new Float32Array(360*3);windGeometry.setAttribute('position',new THREE.BufferAttribute(windPositions,3));const wind=new THREE.Points(windGeometry,dotMaterial('#edc792',3,.65));scene.add(wind);
  const flare=new THREE.Group();flare.position.set(-3.2,.55,.8);scene.add(flare);
  const flash=createSolarFlare(2,new THREE.Vector3(1,.3,.4));sun.add(flash.patch);
  const rays=new THREE.Group();flare.add(rays);for(let i=0;i<9;i++){const direction=new THREE.Vector3(1,(i-4)*.10,Math.sin(i)*.15).normalize();const curve=[new THREE.Vector3(),direction.multiplyScalar(5)];rays.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(curve),new THREE.LineBasicMaterial({color:'#fff0b7',transparent:true,opacity:.32,depthWrite:false})));}
  const cme=new THREE.Group();scene.add(cme);cme.add(new THREE.Mesh(new THREE.SphereGeometry(1,40,28),new THREE.MeshBasicMaterial({color:'#f18e76',transparent:true,opacity:.035,side:THREE.DoubleSide,depthWrite:false})));
  for(let j=0;j<7;j++){const curve=[];for(let i=0;i<=100;i++){const a=i/100*Math.PI*2,b=j/7*Math.PI;curve.push(new THREE.Vector3(Math.cos(a)*Math.sin(b),Math.sin(a),Math.cos(a)*Math.cos(b)));}cme.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(curve),new THREE.LineBasicMaterial({color:'#ed9a7f',transparent:true,opacity:.28,depthWrite:false})));}
  const cloudGeometry=new THREE.BufferGeometry(),cloudPositions=new Float32Array(800*3);for(let i=0;i<800;i++){const y=1-2*(i+.5)/800,a=i*2.399963,r=.82+.18*((i*.754877)%1),rad=Math.sqrt(1-y*y);cloudPositions.set([r*rad*Math.cos(a),r*y,r*rad*Math.sin(a)],i*3);}cloudGeometry.setAttribute('position',new THREE.BufferAttribute(cloudPositions,3));cme.add(new THREE.Points(cloudGeometry,dotMaterial('#f7a88a',3,.75)));
  const labelData=[{text:'太阳 · 静态纹理',id:'sun',point:new THREE.Vector3(-5,-2.4,0)},{text:'日冕 · 增强示意',id:'corona',point:new THREE.Vector3(-5,3.1,0)},{text:'耀斑 · 辐射增强',id:'flare',point:new THREE.Vector3(-2,2.1,.8)},{text:'CME · 等离子体与磁场',id:'cme',point:new THREE.Vector3()}].map(data=>{const label=document.createElement('span');label.className='environment-label';label.textContent=data.text;element.appendChild(label);return {...data,label};});
  let width=1,height=1,raf=0,lastReset=-1;const resize=()=>{width=element.clientWidth;height=element.clientHeight;camera.aspect=width/Math.max(1,height);camera.updateProjectionMatrix();renderer.setSize(width,height);lastReset=-1;};const observer=new ResizeObserver(resize);observer.observe(element);resize();
  const draw=()=>{raf=requestAnimationFrame(draw);const current=latest.current,state=solarDemoState(current.progress);
   if(lastReset!==current.reset){controls.enableDamping=false;controls.update();controls.target.set(.3,0,0);camera.position.set(1,8,Math.max(24,24/camera.aspect));controls.update();controls.enableDamping=true;lastReset=current.reset;}
   corona.visible=current.layers.corona;wind.visible=current.layers.wind;flare.visible=current.layers.flare&&state.flare>0;cme.visible=current.layers.cme&&state.cmeVisible;
   flash.update(current.layers.flare?state.flare:0);rays.scale.setScalar(state.radiationTravel);rays.children.forEach(line=>((line as THREE.Line).material as THREE.LineBasicMaterial).opacity=state.flare*.35);
   cme.position.set(state.cmeX,state.cmeY,0);cme.scale.setScalar(state.cmeRadius);
   for(let i=0;i<360;i++){const y=1-2*(i+.5)/360,a=i*2.399963,rad=Math.sqrt(1-y*y),r=2.5+((i*.381966+state.progress*2)%1)*11;windPositions.set([-5+r*rad*Math.cos(a),r*y,r*rad*Math.sin(a)],i*3);}windGeometry.attributes.position.needsUpdate=true;
   controls.update();for(const data of labelData){if(data.id==='cme')data.point.copy(cme.position).add(new THREE.Vector3(0,-state.cmeRadius-.8,0));const p=data.point.clone().project(camera),visible=data.id==='sun'||data.id==='cme'?data.id==='sun'||cme.visible:data.id==='flare'?flare.visible:corona.visible;data.label.style.display=visible&&p.z>-1&&p.z<1&&Math.abs(p.x)<.91&&Math.abs(p.y)<.9?'block':'none';data.label.style.left=`${(p.x*.5+.5)*width}px`;data.label.style.top=`${(-p.y*.5+.5)*height}px`;}
   renderer.render(scene,camera);
  };draw();return()=>{disposed=true;cancelAnimationFrame(raf);observer.disconnect();controls.dispose();scene.traverse(o=>{if(o instanceof THREE.Mesh||o instanceof THREE.Line||o instanceof THREE.Points){o.geometry.dispose();for(const m of Array.isArray(o.material)?o.material:[o.material]){if('map'in m)(m.map as THREE.Texture|null)?.dispose();m.dispose();}}});renderer.dispose();renderer.domElement.remove();labelData.forEach(d=>d.label.remove());};
 },[]);
 return <div className="environment-canvas" ref={host}>{error&&<p className="environment-error" role="status">{error}</p>}</div>;
}
export function SolarActivity({onClose,onOpenStages,onSun,onEnvironment}:{onClose:()=>void;onOpenStages:()=>void;onSun:()=>void;onEnvironment:()=>void}){
 const [layers,setLayers]=useState(defaultSolarActivityLayers),[progress,setProgress]=useState(.32),[playing,setPlaying]=useState(false),[reset,setReset]=useState(0),root=useRef<HTMLElement>(null),close=useRef<HTMLButtonElement>(null);
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;close.current?.focus();return()=>{if(previous?.isConnected)previous.focus();else document.querySelector<HTMLElement>('.app-header [aria-label="阶段导览"]')?.focus();};},[]);
 useEffect(()=>{if(!playing)return;let raf=0,last=performance.now();const tick=(now:number)=>{const delta=(now-last)/1000;last=now;setProgress(p=>advanceSolarDemo(p,delta));raf=requestAnimationFrame(tick);};raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf);},[playing]);
 useEffect(()=>{if(progress>=1)setPlaying(false);},[progress]);
 const state=solarDemoState(progress);
 const key=(e:KeyboardEvent)=>{e.stopPropagation();if(e.key==='Escape'){e.preventDefault();onClose();}if(e.key==='Tab'){const items=[...root.current!.querySelectorAll<HTMLElement>('button,input,a,summary')].filter(x=>!x.hasAttribute('disabled')&&x.getClientRects().length&&(!x.closest('details:not([open])')||x.matches('summary')));if(e.shiftKey&&document.activeElement===items[0]){e.preventDefault();items.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===items.at(-1)){e.preventDefault();items[0]?.focus();}}};
 return <section ref={root} className="space-environment solar-activity" role="dialog" aria-modal="true" aria-labelledby="solar-activity-title" onKeyDown={key}>
  <header><div><span>07 / SOLAR ACTIVITY</span><h1 id="solar-activity-title">太阳向太空释放了什么？</h1><p>持续太阳风 · 短时辐射增强 · 向外扩展的等离子体云团</p></div><nav><button onClick={onOpenStages}>阶段导览</button><button ref={close} onClick={onClose}>返回原观测</button></nav></header>
  <div className="environment-layout"><div className="environment-stage"><ActivityCanvas layers={layers} progress={progress} reset={reset}/><div className="environment-badge">原理演示 · 非实时太阳活动 · 尺度与速度均经调整</div><div className="solar-demo-controls"><strong>{state.phase}</strong><label>演示进度 · {Math.round(progress*100)}%<input type="range" aria-label="太阳活动演示进度" min="0" max="1" step=".001" value={progress} onChange={e=>{setPlaying(false);setProgress(Number(e.target.value));}}/></label><div><button aria-pressed={playing} onClick={()=>{if(progress>=1)setProgress(0);setPlaying(v=>!v);}}>{playing?'暂停演示':progress>=1?'重播演示':'播放演示'}</button><button onClick={()=>{setPlaying(false);setProgress(0);}}>回到开始</button><button onClick={()=>setReset(n=>n+1)}>复位镜头</button></div></div><p className="environment-caption">拖动旋转 · 滚轮缩放 · 进度只控制本页示意，不改变主页日期<br/>金色点：太阳风；橙色云团：CME。射线与传播节奏为示意，不是抵达时间预测。</p></div>
  <aside><h2>三种现象，分别理解</h2><p>太阳风持续流出；耀斑突出辐射突然增强；CME 则抛出携带磁场的物质云团。它们可有关联，但并非每次耀斑都伴随 CME，也不是每次活动都朝向地球。</p><p className="environment-note">默认暂停在一个示意时刻。同框展示用于比较，不规定事件的先后或必然关系。播放、拖动进度或关闭某层都不会改动主页时间；本图没有当天活动数据。</p><div className="environment-layers">{SOLAR_ACTIVITY_LAYERS.map(layer=><label key={layer.id}><span><input type="checkbox" checked={layers[layer.id]} onChange={e=>setLayers(v=>({...v,[layer.id]:e.target.checked}))}/><i style={{background:layer.color}}/><strong>{layer.name}</strong></span><p>{layer.description}</p></label>)}</div>
   <section className="environment-facts"><h3>光和物质，传播时间不同</h3><p>太阳的光到达地球约需 8 分钟。朝向地球的 CME 常需约 1–3 天，具体依事件而异。本演示将过程压缩到一个短片段，不按这两种真实速度比例运动。</p><p>对地球的影响还与方向、速度、磁场等条件有关，不能只看到一次爆发就断言会出现地磁暴。</p><button onClick={onEnvironment}>接着看地球磁层</button><button onClick={onSun}>进入太阳观测近景</button></section>
   <details><summary>来源与科学边界</summary><p>资料核对：2026-09-24。依据 NASA 科学说明构建形态和过程示意；静态纹理不是实时影像。没有读取实际事件、预测抵达时间或模拟磁重联、等离子体动力学。画面没有按比例放置地球。</p>{SOLAR_ACTIVITY_SOURCES.map(source=><p key={source.url}><a href={source.url} target="_blank" rel="noreferrer">{source.title} ↗</a><small>{source.note}</small></p>)}</details>
  </aside></div>
 </section>;
}
