import {TOPIC_ROUTES,topicSelection,type TopicSelection,type TopicStep} from '../data/topicRoutes';
import './EnvironmentJourneyPanel.css';
export function TopicRoutesPanel({selection,following,reason,onGo,onExit,onRead,onStages,satelliteFailure,onRetrySatellites}:{satelliteFailure:string;onRetrySatellites:()=>void;selection:TopicSelection|null;following:boolean;reason:(step:TopicStep)=>string;onGo:(route:string,index:number)=>void;onExit:()=>void;onRead:()=>void;onStages:()=>void}){
 const current=topicSelection(selection);
 return <section className="environment-journey topic-routes" data-topic-routes aria-label="太阳系专题路线" tabIndex={-1}>
 <details open={current?undefined:true}><summary>六条专题路线 · 整体到细节</summary><p>六章主线用于初次认识；这里按问题重访已接入内容。每条 4–5 步，共用主窗口并保留太阳系日期；恒星固定星表时刻，星系使用概念模型。</p><div className="environment-controls">{TOPIC_ROUTES.map(route=><button key={route.id} data-topic-route={route.id} aria-pressed={current?.route.id===route.id} onClick={()=>onGo(route.id,0)} disabled={!!reason(route.steps[0])} title={reason(route.steps[0])||route.question}>{route.name} · {route.steps.length} 步</button>)}</div><button onClick={onStages}>检查所需阶段</button></details>
 {satelliteFailure&&<div role="alert" data-topic-satellite-error><p>{satelliteFailure}。缺失成员已隐藏，请重试后继续。</p><button onClick={onRetrySatellites}>重试本专题卫星历表</button></div>}
 {current&&<article data-topic-current><p>{current.route.name} · 第 {current.index+1} / {current.route.steps.length} 步</p><h3>{current.step.title}</h3><strong role="status">{following?'本步画面已定位':reason(current.step)||'已离开本步，可重新定位后继续'}</strong><p>{current.step.look}</p><p className="environment-legend">{current.step.limit}</p><small>本专题切换暂停运动，保留日期；播放、步进和详细来源请查看对应模块。</small><div className="environment-controls"><button disabled={!!reason(current.step)} onClick={()=>onGo(current.route.id,current.index)}>重新定位本步</button><button onClick={onRead} disabled={!following}>查看本步模块与来源</button></div><p>{current.index+1<current.route.steps.length?`下一步：${current.route.steps[current.index+1].title}`:'已到本专题末步，可返回全景再选另一条路线。'}</p><div className="environment-controls"><button disabled={current.index===0||!!reason(current.route.steps[current.index-1])} title={current.index?reason(current.route.steps[current.index-1]):'第一步'} onClick={()=>onGo(current.route.id,current.index-1)}>专题上一步</button><button disabled={current.index===current.route.steps.length-1||!!reason(current.route.steps[current.index+1])} title={current.index+1<current.route.steps.length?reason(current.route.steps[current.index+1]):'最后一步'} onClick={()=>onGo(current.route.id,current.index+1)}>专题下一步</button></div>{current.index+1<current.route.steps.length&&reason(current.route.steps[current.index+1])&&<p role="status">下一步：{reason(current.route.steps[current.index+1])}</p>}<button onClick={onExit}>退出专题并恢复全景</button></article>}
 </section>;
}
