import { readFileSync, writeFileSync } from 'node:fs';
import { CONTENT_COVERAGE, COVERAGE_DATASETS } from '../src/data/contentCoverage';
import { MASTER_PLAN } from '../src/data/masterPlan';
import { DELIVERY_BATCHES, SCOPE_ADDITIONS } from '../src/data/executionPlan';
import { CLOSEOUT_STEPS, COVERAGE_AUDIT, OPEN_FINDINGS, RESOLVED_FINDINGS, CURRENT_RELEASE, FINAL_CLOSEOUT } from '../src/data/closeoutPlan';
import { OBSERVATION_COUNTS } from '../src/data/observationCatalog';
const lines = (values: string[]) => values.map(s => `- ${s}`).join('\n');
const source = (p: string) => `[${p.split('/').at(-1)}](../${p})`;
const stamp = `当前规划版本 ${CURRENT_RELEASE.version}；能力基线 r09.3 已上线。本版范围冻结，技术收尾及本轮用户确认通过，当前版本冻结；详见 FINAL-TECHNICAL-REPORT.md；太阳系动态天体数量未变。本轮验收记录见 ACCEPTANCE-RECORD.md。`;
const table = ['| 编号 | 内容 | 当前层级 | 待核对与边界 |','| --- | --- | --- | --- |',...CONTENT_COVERAGE.map(r=>`| ${r.id} | ${r.title} | ${r.status} | ${r.target} |`)].join('\n');
const audit = COVERAGE_AUDIT.map(row=>{
 const topic=CONTENT_COVERAGE.find(r=>r.id===row.id),addition=SCOPE_ADDITIONS.find(r=>r.id===row.id);
 return `### ${row.id} · ${topic?.title??addition?.title}\n\n当前：${topic?.current??addition?.status}\n\n核对层级：${row.review}。版本整体验收通过；本项未单独登记。\n\n操作：${row.check}\n\n已有证据：${row.reports.map(source).join('、')}。${row.findingIds.length?`关联未关闭事项：${row.findingIds.join('、')}。`:''}`;
}).join('\n\n');
const files:Record<string,string>={};
files['docs/FIRST-RELEASE-CLOSEOUT.md']=`# 太阳系认知版 · 首版收尾与 25 项核对表\n\n${stamp}\n\n## 本版固定的三步收尾\n\n${FINAL_CLOSEOUT.map(s=>`### ${s.title}\n\n状态：${s.status}。${s.detail}`).join('\n\n')}\n\n仅影响正常使用或造成错误理解的问题阻止交付；美化、新天体、新玩法与精度提升留给后续，不再扩展本版。\n\n## 既有五步台账与证据\n\n${CLOSEOUT_STEPS.map(s=>`### ${s.id} · ${s.title}\n\n状态：${s.status}。\n\n${s.done}`).join('\n\n')}\n\n第 1 步完成整理；第 2 步已建立 20 类主题 + 5 项必补的代码/证据核对表，E01–E20 与 S01–S05 已完成入口及代表操作检查，固定七组最终回归亦通过；技术证据已补齐，本轮用户确认已完成，实际设备差异与长期表现保留为已知限制。这不是五次提交或完成百分比，也不是所有星体都已收录。\n\n完成条件：约定主要构成和代表体验达到标准，科学与体验证据齐备，关键问题关闭并由用户明确验收。新发现归入既有步骤；范围变更须说明原因并确认，不静默取消原标准。\n\n## 本版未关闭事项：${OPEN_FINDINGS.length} 项\n\n本轮验收事项已按确认范围关闭。后续发现另行登记，不自动增加本版优化。\n\n${OPEN_FINDINGS.map(f=>`### ${f.id} · ${f.title}\n\n${f.kind} · ${f.packages.join(' / ')} · 未关闭\n\n当前：${f.current}\n\n关闭标准：${f.close}\n\n依据：${f.evidence.map(source).join('、')}。`).join('\n\n')}\n\n## 已完成的收尾与用户确认\n\n${RESOLVED_FINDINGS.map(f=>`### ${f.id} · ${f.title}\n\n${f.status}。${f.result}\n\n依据：${f.evidence.map(source).join('、')}。`).join('\n\n')}\n\n## 25 项核对表\n\n已核对源码入口和既有报告，不将原报告检查冒充本轮重新计算或用户视觉验收。网页入口：更多工具 → 整体规划 → 收尾进度；每项可进入元素覆盖，再打开现有观察入口。\n\n${audit}\n\n## 明确后置\n\n${SCOPE_ADDITIONS.filter(s=>s.id>'S05').map(s=>`- ${s.id} ${s.title}：${s.level}；${s.deferred}`).join('\n')}\n\n全部已知成员、精细地形、实时天气、完整姿态、空间天气预报、飞船/碰撞/仙侠等未实现能力，不因本次整理变为已完成。F01 原标准差距已修复，保留关闭依据；本轮验收通过，版本冻结，详细范围见 [确认记录](ACCEPTANCE-RECORD.md)。\n`;
files['docs/CONTENT-COVERAGE.md']=`# 太阳系 20 类内容覆盖 · 当前台账\n\n${stamp}\n\n${table}\n\n## 入口、数据与证据\n\n${CONTENT_COVERAGE.map(r=>`### ${r.id} · ${r.title}\n\n状态：${r.status}；${r.acceptance}。\n\n当前：${r.current}\n\n待核对与边界：${r.target}\n\n表示依据：${r.evidence}。入口操作：${r.how}\n\n已记录验证：${r.validation}\n\n发布：${r.release}\n\n实现模块：${r.modules.map(source).join('、')}。\n\n${r.datasets.map(k=>{const d=COVERAGE_DATASETS[k];return `数据：${d.version}；${d.startUtc} 至 ${d.endUtc}；[包清单](../public/${d.path})。`;}).join('\n\n')}`).join('\n\n')}\n\n完整验收动作、报告及未关闭事项见 [25 项核对表](FIRST-RELEASE-CLOSEOUT.md)。[旧版覆盖台账归档](history/CONTENT-COVERAGE-before-closeout.md) 保留历史状态，不作为当前进度。\n`;
files['docs/EXECUTION-PLAN.md']=`# R01–R09 交付归属与首版收尾\n\n${stamp}\n\n接下来的顺序固定为 [C01–C05 五步收尾](FIRST-RELEASE-CLOSEOUT.md)，不重新从 R01 开发。R01–R09 保留内容和原验收标准，主页九批图层开关是另一套显示控制。\n\n${DELIVERY_BATCHES.map(b=>`## ${b.id} · ${b.title}\n\n当前：${b.status}。\n\n归属：${b.packages.join(' / ')}；主题：${b.topics.join('、')}。\n\n前置：${b.dependency}\n\n### 原定必须内容\n\n${lines(b.must)}\n\n### 验收标准\n\n${lines(b.acceptance)}\n\n边界：${b.boundary}`).join('\n\n')}\n\n## 五项必补与后置范围\n\n${SCOPE_ADDITIONS.map(s=>`### ${s.id} · ${s.title}\n\n层级：${s.level}；状态：${s.status}。\n\n范围：${s.scope}\n\n验收：${s.acceptance}\n\n延期：${s.deferred}\n\n${s.sources.map((url,i)=>`[来源 ${i+1}](${url})`).join('、')}`).join('\n\n')}\n\n[旧版执行记录归档](history/EXECUTION-PLAN-before-closeout.md) 保留历史，不覆盖当前状态。\n`;
files['docs/MASTER-PLAN.md']=`# ORBIT · 太阳系认知版总规划\n\n${stamp}\n\n## 当前在哪里\n\n${OBSERVATION_COUNTS.allDynamic} 个当前动态对象，包含 27 颗选定卫星/伴星；另有 1 个独立历史案例。14 节运动课、六条专题 27 步、独立 Hipparcos 恒星视图已有实现。发布、自动检查和用户验收分别记录。\n\n## 接下来还有多少\n\n统一采用 [五步收尾与 25 项核对表](FIRST-RELEASE-CLOSEOUT.md)。三步收尾已完成：技术测量、固定回归及本轮用户确认。当前认知版冻结，后续需求与问题另行安排。原 M0–M6 的 7 个里程碑、21 个工作包保留归属，不等于还有 21 轮开发。\n\n## 20 类主题\n\n${table}\n\n具体入口、数据版本与验证记录见 [内容覆盖](CONTENT-COVERAGE.md)。\n\n## 七个里程碑与原完成标准\n\n${MASTER_PLAN.phases.map(m=>`### ${m.id} · ${m.title}\n\n状态：${m.status}。目标：${m.goal}\n\n依赖：${m.dependency}\n\n${m.packages.map(w=>`#### ${w.id} · ${w.title}\n\n范围：${w.scope}\n\n完成标准：${w.acceptance}`).join('\n\n')}`).join('\n\n')}\n\n## 数据到产品\n\n来源快照 → 身份/单位/时间/坐标检查 → 本地分包和误差验证 → 共用供数与场景 → 参数和来源说明 → 用户验收。物理求解仍为十体牛顿近似；观测目标增加不自动进入积分器。\n\n${MASTER_PLAN.sources.map(s=>`- [${s.title}](${s.url})：${s.use}`).join('\n')}\n\n## 后续分支\n\n${MASTER_PLAN.branches.map(b=>`### ${b.id} · ${b.title}\n\n启动条件：${b.dependency}\n\n${b.scope}`).join('\n\n')}\n\n## 完成判据与范围控制\n\n20 类主题及 S01–S05 达到各自约定层级，六条路线走通，科学与性能证据齐备、关键问题关闭，并由用户明确验收。F01 已在主全景接入固定星表并验证方向，关闭依据保留；本轮用户确认通过；不推定全部设备与长时表现。真实设备帧率和长期体验不得由无头浏览器的提交速率代替。\n\n所有已知对象、实时天气、全部地形和历史事件不属于首版完整性承诺。阶段开关控制显示，收尾表控制当前工作，建设记录保留每批交付。\n\n[旧版总规划归档](history/MASTER-PLAN-before-closeout.md) 保留原始记录；本页与网页数据由同一台账生成。\n`;
let mismatch=false;
for(const [path,text] of Object.entries(files)){
 if(process.argv.includes('--check')){if(readFileSync(path,'utf8').replace(/\r\n/g,'\n')!==text){console.error('Planning document out of sync:',path);mismatch=true;}}
 else writeFileSync(path,text,'utf8');
}
if(mismatch)process.exitCode=1;
else console.log(process.argv.includes('--check')?'Planning documents synchronized':'Updated four planning documents');
