import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {interpolateChunk} from '../src/ephemeris/ephemeris';
import {SOLAR_REFERENCE_TDB,SOLAR_START,SOLAR_END,SOLAR_ECLIPSE_SOURCE,solarShadow,minimumSolarAxis} from '../src/data/solarEclipse';
import {tdbToUtc} from '../src/data/time';
const raw=readFileSync('public/data/2026-08.json'),chunk=JSON.parse(raw.toString()),sample=(t:number)=>interpolateChunk(chunk,t);
const minimum=minimumSolarAxis(sample),g=solarShadow(sample(minimum))!;
const report={version:'solar-eclipse-2026-08-12-geometric-v1',sourceCredit:"Eclipse Predictions by Fred Espenak, NASA's GSFC",sources:[SOLAR_ECLIPSE_SOURCE,'https://science.nasa.gov/eclipses/types/'],reference:{ttLabel:'2026-08-12 17:47:05.2 TT (TDT)',tdb:SOLAR_REFERENCE_TDB,utcUsingProjectLeapSeconds:tdbToUtc(SOLAR_REFERENCE_TDB).toISOString(),catalogUtLabel:'2026-08-12 17:45:53.8 UT',catalogDeltaTSeconds:71.4},model:{minimumTdb:minimum,minimumUtc:tdbToUtc(minimum).toISOString(),deltaSeconds:minimum-SOLAR_REFERENCE_TDB,axisDistanceKm:g.offsetKm,surfaceUmbraKm:g.surfaceUmbraKm,stage:g.stage},input:{file:'data/2026-08.json',sha256:createHash('sha256').update(raw).digest('hex'),positionSource:'NASA/JPL Horizons',frame:'ECLIPJ2000',stateKind:'display centers',correction:'NONE',radii:'project JPL mean radii',timeScale:'TDB seconds since J2000'},window:{start:SOLAR_START,end:SOLAR_END},limits:['Earth-centered shadow-axis frame; all lengths in km. Surface classification uses the sphere intersection, not the Earth-center plane.','No geographic mapping, local circumstances, light-time, aberration, Earth oblateness, lunar topography or radiometry.','Independent geometric closest-axis time is compared in TDB with NASA TT; this is model discrepancy, not interpolation error.','Single event bracket; not a general event or hybrid eclipse solver.'],curve:Array.from({length:97},(_,i)=>{const time=SOLAR_START+i*300,s=solarShadow(sample(time))!;return {time,offsetKm:s.offsetKm,axisHits:s.axisHits,penumbraTouches:s.penumbraTouches};})};
mkdirSync('public/data/events',{recursive:true});writeFileSync('public/data/events/solar-2026-08-12.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report.model,null,2));
