import { useCallback, useEffect, useRef, useState, type CSSProperties } from 'react';
import { Activity, ArrowUpRight, BookOpen, CalendarDays, ChevronDown, ChevronLeft, ChevronRight, Circle, CircleHelp, Cloud, Compass, Crosshair, Globe2, Grid3X3, Info, Layers3, LoaderCircle, Maximize2, Orbit, Pause, Play, RotateCcw, Ruler, Route, ScanLine, Sparkles, TrendingUp, Wind, X } from 'lucide-react';
import { BODIES, bodyById } from './data/catalog';
import { publicAsset } from './data/publicAsset';
import { SATELLITES, satelliteById } from './data/satellites';
import { OBSERVATION_COUNTS, SATELLITE_PARENTS } from './data/observationCatalog';
import { tdbToUtc, utcToTdb } from './data/time';
import { BODY_IDS, type BodyDefinition, type BodyId, type CameraView, type StateFrame, type ViewOptions } from './types';
import { useSimulation } from './hooks/useSimulation';
import { useSatellites } from './hooks/useSatellites';
import { useOverviewSatellites } from './hooks/useOverviewSatellites';
import { SolarSystem } from './components/SolarSystem';
import { ValidationPanel } from './components/ValidationPanel';
import { ExplorationGuide, type ObservationTour } from './components/ExplorationGuide';
import { SatelliteSystem } from './components/SatelliteSystem';
import { SatelliteChildren, SatelliteInspector } from './components/SatellitePanels';
import { ExpansionRoadmap } from './components/ExpansionRoadmap';
import './styles.css';

const AU = 149597870.7;
const initialOptions: ViewOptions = { view: 'overview', comparisonSet: 'planets', presentation: 'spatial', exaggerated: false, trajectories: true, referencePlane: false, velocityVectors: false, belts: true, scale: true, earthClouds: true, earthAtmosphere: true, cameraAngle: 'perspective', cameraOrbit: typeof window === 'undefined' || !window.matchMedia('(prefers-reduced-motion: reduce)').matches };
const regionViews: CameraView[] = ['overview', 'inner', 'outer', 'earth-moon'];
const views: { id: CameraView; label: string }[] = [{ id: 'overview', label: '太阳系全景' }, { id: 'inner', label: '内行星' }, { id: 'outer', label: '外行星' }, { id: 'earth-moon', label: '地月系统' }, { id: 'comparison', label: '大小对比' }];
const speeds = [{ value: 1, label: '1×' }, { value: 3600, label: '1 小时/s' }, { value: 21600, label: '6 小时/s' }, { value: 86400, label: '1 天/s' }, { value: 8640000, label: '100 天/s' }];
const satelliteParents = SATELLITE_PARENTS;
const satelliteSpeed = (parent: BodyId) => parent === 'mars' ? 3600 : 21600;
const kinds = { star: '恒星', planet: '行星', moon: '天然卫星' };
const materialNames: Record<BodyId, string> = { sun: '等离子体', mercury: '岩质行星', venus: '岩质行星', earth: '岩质行星', moon: '岩质卫星', mars: '岩质行星', jupiter: '气态巨行星', saturn: '气态巨行星', uranus: '冰巨星', neptune: '冰巨星' };
const formatNumber = (n: number, digits = 2) => n.toLocaleString('zh-CN', { maximumFractionDigits: digits, minimumFractionDigits: digits });
const toUtcMs = (tdb: number) => { const value = tdbToUtc(tdb); return value instanceof Date ? value.getTime() : Number(value); };
const beijingInput = (tdb: number) => new Date(toUtcMs(tdb) + 8 * 3600e3).toISOString().slice(0, 19);

function Orb({ body, large = false }: { body: BodyDefinition; large?: boolean }) { return <span aria-hidden="true" className={`body-orb ${body.id} ${large ? 'inspector-big-orb' : ''}`} style={{ '--body-color': body.color } as CSSProperties}/>; }
function Mass({ value }: { value: number }) { const [base, exponent] = value.toExponential(3).split('e'); return <>{base} × 10<sup>{Number(exponent)}</sup><small>kg</small></>; }
function Property({ name, children }: { name: string; children: React.ReactNode }) { return <div className="property"><dt>{name}</dt><dd>{children}</dd></div>; }

interface EarthLayerControls {
  clouds: boolean; atmosphere: boolean;
  onClouds: () => void; onAtmosphere: () => void; onObserve: () => void;
}

function EarthLayers({ controls }: { controls: EarthLayerControls }) {
  return <div className="earth-layer-controls"><div className="earth-layer-heading"><span>地球的云与大气</span><small>VISUAL LAYERS</small></div><div className="earth-layer-toggles"><button className={controls.clouds ? 'active' : ''} onClick={controls.onClouds} aria-pressed={controls.clouds} aria-label="显示地球云层"><Cloud size={13}/>云层<i/></button><button className={controls.atmosphere ? 'active' : ''} onClick={controls.onAtmosphere} aria-pressed={controls.atmosphere} aria-label="显示地球大气层"><Wind size={13}/>大气层<i/></button></div><button className="earth-atmosphere-action" onClick={controls.onObserve}>观察地球大气<ArrowUpRight size={12}/></button><p>云层为静态云图，大气辉光为散射示意；不表示实时气象。</p></div>;
}

function OverviewMembers({ physics, loadedCount, loading, error, onRetry, onSun, onPlanets, onEarthMoon, onSatelliteSystem, onAtlas, onRoadmap }: { physics: boolean; loadedCount: number; loading: boolean; error: string; onRetry: () => void; onSun: () => void; onPlanets: () => void; onEarthMoon: () => void; onSatelliteSystem: (parent: BodyId) => void; onAtlas: () => void; onRoadmap: () => void }) {
  const [expanded, setExpanded] = useState(false);
  return <section className={`overview-members ${expanded ? 'expanded' : ''}`} aria-label="已接入天体范围"><button className="overview-members-toggle" onClick={() => setExpanded(value => !value)} aria-expanded={expanded} title={`本观测站已接入${OBSERVATION_COUNTS.dynamic}个动态天体及${OBSERVATION_COUNTS.knowledgeOnly}个资料天体，并非太阳系的全部天体`}><Layers3 size={13}/><span>已接入天体</span><small>{physics ? '10 体推演' : `${loadedCount}/${OBSERVATION_COUNTS.dynamic} 已加载`}</small><ChevronDown size={12}/></button>{expanded && <div className="overview-members-content"><div className="overview-member-counts"><button onClick={onSun}><strong>1</strong><span>太阳</span></button><button onClick={onPlanets}><strong>8</strong><span>行星</span></button><span><strong>{OBSERVATION_COUNTS.satellites}</strong><span>选定卫星</span></span><button className="atlas-count-link" onClick={onAtlas}><strong>{OBSERVATION_COUNTS.knowledgeOnly}</strong><span>更多图鉴<ArrowUpRight size={9}/></span></button></div><p className="overview-member-key"><i/>当前接入 {OBSERVATION_COUNTS.dynamic} 个动态天体；不是太阳系总数。另有 {OBSERVATION_COUNTS.knowledgeOnly} 个资料天体。</p><div className="overview-family-links"><button onClick={onEarthMoon}><i style={{ background: bodyById.earth.color }}/>地球家族<small>月球</small><ChevronRight size={10}/></button>{satelliteParents.map(parent => <button key={parent} onClick={() => onSatelliteSystem(parent)}><i style={{ background: bodyById[parent].color }}/>{bodyById[parent].name}家族<small>{SATELLITES.filter(body => body.parentId === parent).length} 颗已接入</small><ChevronRight size={10}/></button>)}</div><p className="overview-member-note">{physics ? '当前物理验证仍为太阳、8 颗行星与月球的十体模型。点击家族可返回真实历表观测。' : '太阳系还有更多卫星、矮行星、小行星与彗星，当前尚未全部接入。带区散点仅示意分布区域，不代表真实数量或逐体轨道。'}</p><button className="overview-roadmap-link" onClick={onRoadmap}><Route size={13}/><span>更多天体与玩法 · 扩展路线</span><ArrowUpRight size={12}/></button></div>}{!physics && (loading || error) && <div className="overview-member-status" aria-live="polite">{error ? <><Info size={11}/><span>部分卫星加载失败</span><button onClick={onRetry}>重试</button></> : <><LoaderCircle size={11} className="spin"/><span>正在同步卫星家族…</span></>}</div>}</section>;
}

function MotionComparison({ frame }: { frame: StateFrame | null }) {
  return <details className="motion-comparison"><summary>比较行星的运行速度<ChevronDown size={12}/></summary><p>同一时刻，相对太阳的速度。公转周期是参考值，速度会沿轨道变化。</p><table><caption className="sr-only">行星当前速度和公转周期比较</caption><thead><tr><th>行星</th><th>km/s</th><th>公转一周</th></tr></thead><tbody>{BODIES.filter(body => body.kind === 'planet').map(body => {
    const i = BODY_IDS.indexOf(body.id) * 3;
    const velocity = frame ? Math.hypot(...[0,1,2].map(axis => frame.velocities[i+axis] - frame.velocities[axis])) : null;
    return <tr key={body.id}><td><i style={{ background: body.color }}/>{body.name}</td><td>{velocity === null ? '—' : formatNumber(velocity, 2)}</td><td>{body.orbitalPeriodDays > 730 ? `${formatNumber(body.orbitalPeriodDays / 365.25, 1)} 年` : `${formatNumber(body.orbitalPeriodDays, 0)} 天`}</td></tr>;
  })}</tbody></table></details>;
}

function Inspector({ selectedId, frame, mode, onFollow, onSystem, earthControls }: { selectedId: BodyId; frame: StateFrame | null; mode: 'ephemeris' | 'physics'; onFollow: () => void; onSystem?: () => void; earthControls?: EarthLayerControls }) {
  const body = bodyById[selectedId];
  const index = BODY_IDS.indexOf(selectedId) * 3;
  const referenceId = selectedId === 'moon' ? 'earth' : selectedId === 'sun' ? null : 'sun';
  const referenceIndex = referenceId === null ? -1 : BODY_IDS.indexOf(referenceId) * 3;
  const referenceName = referenceId === null ? '太阳系质心（SSB）' : bodyById[referenceId].name;
  let distance = 0, speed = 0;
  if (frame) { for (let i = 0; i < 3; i++) { distance += (frame.positions[index+i] - (referenceIndex < 0 ? 0 : frame.positions[referenceIndex+i])) ** 2; speed += (frame.velocities[index+i] - (referenceIndex < 0 ? 0 : frame.velocities[referenceIndex+i])) ** 2; } distance = Math.sqrt(distance); speed = Math.sqrt(speed); }
  return <aside className="inspector" aria-label="天体详情">
    <div className="inspector-header"><div className="eyebrow">CELESTIAL PROFILE</div><div className="inspector-title-line"><h2>{body.name}</h2><Orb body={body} large/></div><div className="inspector-english">{body.englishName.toUpperCase()}</div><div className="body-type"><span className="tag">{kinds[body.kind]}</span><span className="material-tag">{materialNames[selectedId]}</span><span>{selectedId === 'sun' ? '太阳系的引力中心' : selectedId === 'moon' ? '地球唯一的天然卫星' : `距日第 ${BODY_IDS.filter(id => id !== 'sun' && id !== 'moon').indexOf(selectedId) + 1} 颗行星`}</span></div><p className="body-description">{body.description}</p>{selectedId === 'earth' && <p className="material-note">约 71% 表面为海洋，仍有岩石地壳与大陆。蔚蓝是它的表面特征，不代表它是一颗液态星球。</p>}{selectedId === 'sun' && <p className="material-note">炽热的等离子体恒星，由核聚变供能，并非普通燃烧的火球。日冕与日珥为增强示意。</p>}<button className="follow-button" onClick={onFollow}><Crosshair size={13}/> 跟随{body.name}<ArrowUpRight size={12}/></button>{onSystem && <button className="follow-button related-system-button" onClick={onSystem}><Orbit size={13}/>{selectedId === 'earth' || selectedId === 'moon' ? '观看地月公转' : `观察${body.name}的卫星`}<ArrowUpRight size={12}/></button>}</div>
    {earthControls && <EarthLayers controls={earthControls}/>}
    <div className="inspector-section"><h3 className="section-label"><Circle size={12}/>物理参数</h3><dl className="property-grid"><Property name="平均半径">{formatNumber(body.radiusKm, body.radiusKm < 3000 ? 1 : 0)}<small>km</small></Property><Property name="质量"><Mass value={body.massKg}/></Property><Property name="恒星自转周期">{formatNumber(Math.abs(body.rotationHours), 2)}<small>小时{body.rotationHours < 0 ? ' · 逆行' : ''}</small></Property><Property name="公转周期">{body.orbitalPeriodDays > 0 ? <>{formatNumber(body.orbitalPeriodDays, 2)}<small>天</small></> : <span>—<small>太阳系中心恒星</small></span>}</Property><Property name="自转轴倾角">{formatNumber(body.obliquityDeg, 2)}<small>°</small></Property><Property name="轨道半长轴">{body.semiMajorAxisAu > 0 ? <>{formatNumber(body.semiMajorAxisAu, selectedId === 'moon' ? 5 : 3)}<small>AU</small></> : '—'}</Property></dl></div>
    <div className="inspector-section"><div className="realtime-title"><h3 className="section-label"><Activity size={13}/>当前状态</h3><span className="live-badge"><i className="status-dot"/>{mode === 'ephemeris' ? 'EPHEMERIS' : 'SIMULATION'}</span></div><div className="state-value"><span>相对距离</span><strong>{frame ? formatNumber(distance / (selectedId === 'moon' ? 1 : AU), selectedId === 'moon' ? 0 : 4) : '—'}<small>{selectedId === 'moon' ? 'km' : 'AU'}</small></strong></div><div className="state-value"><span>相对速度</span><strong>{frame ? formatNumber(speed, selectedId === 'sun' ? 4 : 2) : '—'}<small>km/s</small></strong></div><p className="reference-note">参照对象：{referenceName}<br/>{mode === 'physics' && body.displayNaifId !== body.simulationNaifId ? '当前为行星系统质心，采用系统总引力参数。' : '几何位置 · 未作光行时修正'}</p></div>
    <div className="inspector-section"><p className="body-fact"><Sparkles size={13}/>{body.fact}</p><MotionComparison frame={frame}/></div>
    <div className="inspector-source"><details><summary>数据、图像与科学边界<ChevronDown size={12}/></summary><div className="source-details"><p>位置与速度：<a href="https://ssd.jpl.nasa.gov/horizons/" target="_blank" rel="noreferrer">NASA / JPL Horizons</a>；坐标系 ECLIPJ2000，太阳系质心为原点，计算时间为 TDB。</p><p>物理参数：<a href={body.sourceUrl} target="_blank" rel="noreferrer">JPL / NASA 来源资料</a>。自转与轴倾为参考近似，月球半长轴相对地球。</p><p>行星贴图：<a href="https://www.solarsystemscope.com/textures/" target="_blank" rel="noreferrer">Solar System Scope / INOVE</a>，<a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noreferrer">CC BY 4.0</a>。以 NASA 资料为基础的静态纹理，包含颜色调整与重建区域，不是实时影像。贴图文件未修改，场景另行计算光照与大气。</p><p>行星自转与朝向使用参考模型。小行星带、柯伊伯带为区域范围示意，随机点没有逐体真实轨道，也不代表实际天体数量。</p><p>物理验证采用牛顿点质量多体引力，未包含相对论、非球形引力及全部小天体，不用于航天导航。</p><a href={publicAsset('/data/manifest.json')} target="_blank" rel="noreferrer">历表版本与来源清单 ↗</a> · <a href={publicAsset('/textures/sources.json')} target="_blank" rel="noreferrer">贴图来源清单 ↗</a></div></details></div>
  </aside>;
}

export default function App() {
  const simulation = useSimulation();
  const { frame, manifest, mode, setMode, playing, setPlaying, speed, setSpeed, loading, error, setError, seek, goNow, reset, physicsEpoch, actualSpeed, pendingSeconds } = simulation;
  const [selectedId, setSelectedId] = useState<BodyId>('earth');
  const [options, setOptions] = useState<ViewOptions>(initialOptions);
  const [satelliteView, setSatelliteView] = useState(false);
  const [satelliteParent, setSatelliteParent] = useState<BodyId>('jupiter');
  const [selectedSatelliteId, setSelectedSatelliteId] = useState<string | null>(null);
  const satelliteData = useSatellites(satelliteParent, frame?.time, satelliteView && mode === 'ephemeris');
  const overviewSatelliteData = useOverviewSatellites(frame?.time, mode === 'ephemeris' && !satelliteView && ['overview', 'inner', 'outer', 'follow'].includes(options.view));
  const systemSatellites = SATELLITES.filter(body => body.parentId === satelliteParent);
  const [showReport, setShowReport] = useState(false);
  const [showHelp, setShowHelp] = useState(false);
  const [showRoadmap, setShowRoadmap] = useState(false);
  const closeRoadmap = useCallback(() => setShowRoadmap(false), []);
  const [guideTab, setGuideTab] = useState<'atlas' | 'tours' | null>(null);
  const [guideBodyId, setGuideBodyId] = useState<string>();
  const [immersive, setImmersive] = useState(false);
  const [editingDate, setEditingDate] = useState(false);
  const dateInput = useRef<HTMLInputElement>(null);
  const dateCommitted = useRef(false);
  const [canvasReady, setCanvasReady] = useState(false);
  const [catalogOpen, setCatalogOpen] = useState(false);
  const [inspectorOpen, setInspectorOpen] = useState(false);
  const openRoadmap = () => { setShowRoadmap(true); setGuideTab(null); setShowHelp(false); setShowReport(false); setCatalogOpen(false); setInspectorOpen(false); };
  const exploreFromRoadmap = useCallback(() => { setShowRoadmap(false); setCatalogOpen(true); setInspectorOpen(false); }, []);
  const validationFromRoadmap = useCallback(() => { setShowRoadmap(false); setShowReport(true); }, []);
  const currentDate = frame ? beijingInput(frame.time) : '';
  useEffect(() => { if (!editingDate && dateInput.current) dateInput.current.value = currentDate; }, [currentDate, editingDate]);
  const toggleOption = (name: keyof Omit<ViewOptions, 'view' | 'comparisonSet' | 'presentation' | 'cameraAngle'>) => setOptions(o => ({ ...o, [name]: !o[name] }));
  const stopCameraOrbit = useCallback(() => setOptions(o => o.cameraOrbit === false ? o : { ...o, cameraOrbit: false }), []);
  const chooseView = (view: CameraView) => {
    setSatelliteView(false); setSelectedSatelliteId(null);
    if (view === 'earth-moon') setSelectedId('earth');
    if (view === 'comparison' && options.comparisonSet !== 'all' && (selectedId === 'sun' || (options.comparisonSet === 'rocky' && ['jupiter','saturn','uranus','neptune'].includes(selectedId)))) setSelectedId('earth');
    setOptions(o => ({ ...o, view, presentation: regionViews.includes(view) ? 'spatial' : o.presentation, trajectories: view === 'overview' ? true : regionViews.includes(view) ? false : o.trajectories, belts: view === 'overview' ? true : o.belts, exaggerated: false }));
  };
  const chooseComparisonSet = (comparisonSet: 'rocky' | 'planets' | 'all') => {
    if (comparisonSet !== 'all' && (selectedId === 'sun' || (comparisonSet === 'rocky' && ['jupiter','saturn','uranus','neptune'].includes(selectedId)))) setSelectedId('earth');
    setOptions(o => ({ ...o, comparisonSet }));
  };
  const chooseMode = (next: 'ephemeris' | 'physics') => { setShowRoadmap(false); setGuideTab(null); setShowReport(false); if (next === 'physics' && satelliteView) { setSatelliteView(false); setOptions(o => ({ ...o, view: 'follow' })); } setMode(next); };
  const inspectBody = (id: BodyId) => { setSatelliteView(false); setSelectedSatelliteId(null); setSelectedId(id); setOptions(o => ({ ...o, view: 'follow' })); setCatalogOpen(false); };
  const observeEarthAtmosphere = () => { inspectBody('earth'); setOptions(o => ({ ...o, earthAtmosphere: true })); };
  const openSatelliteSystem = (parent: BodyId, selected: string | null = null, autoplay = true) => {
    const entering = !satelliteView || parent !== satelliteParent;
    setGuideTab(null); setShowReport(false); setSatelliteView(true); setSatelliteParent(parent); setSelectedSatelliteId(selected); setSelectedId(parent); setMode('ephemeris'); setCatalogOpen(false);
    if (entering) { if (autoplay) { setSpeed(3600); setPlaying(true); } setOptions(o => ({ ...o, presentation: 'spatial', trajectories: true, exaggerated: false })); }
  };
  const playSatelliteOrbits = () => { setSelectedSatelliteId(null); setSpeed(satelliteSpeed(satelliteParent)); setPlaying(true); setOptions(o => ({ ...o, trajectories: true })); };
  const watchEarthMoon = () => { chooseView('earth-moon'); setMode('ephemeris'); setSpeed(86400); setPlaying(true); setCatalogOpen(false); };
  const openRelatedSystem = () => { if (selectedId === 'earth' || selectedId === 'moon') watchEarthMoon(); else if (satelliteParents.includes(selectedId)) openSatelliteSystem(selectedId); };
  const stepBody = (direction: number) => inspectBody(BODY_IDS[(BODY_IDS.indexOf(selectedId) + direction + BODY_IDS.length) % BODY_IDS.length]);
  const openGuide = (tab: 'atlas' | 'tours', bodyId?: string) => { setShowRoadmap(false); setGuideTab(tab); setGuideBodyId(bodyId); setShowReport(false); setCatalogOpen(false); setInspectorOpen(false); };
  const observeTour = (tour: ObservationTour) => {
    if (tour.satelliteParentId) { openSatelliteSystem(tour.satelliteParentId); setSpeed(tour.speed); setPlaying(tour.playing); return; }
    setSatelliteView(false); setSelectedSatelliteId(null);
    setGuideTab(null); setMode('ephemeris'); setSelectedId(tour.bodyId); setSpeed(tour.speed); setPlaying(tour.playing);
    setOptions(o => ({ ...o, view: tour.view, presentation: 'spatial', exaggerated: false, trajectories: tour.id === 'motion', velocityVectors: tour.view === 'inner' }));
  };
  useEffect(() => { const key = (e: KeyboardEvent) => { if (e.code === 'Escape') { setShowReport(false); setShowHelp(false); setGuideTab(null); } if (e.target instanceof HTMLElement && e.target.closest('input,select,textarea,button,a,[contenteditable="true"]')) return; if (e.code === 'Space') { e.preventDefault(); setPlaying(p => !p); } }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key); }, [setPlaying]);
  function commitDate(value: string) {
    if (dateCommitted.current) return;
    dateCommitted.current = true; setEditingDate(false);
    if (!value) return;
    const ms = Date.parse(`${value}+08:00`);
    if (!Number.isFinite(ms)) { setError('请输入有效的北京时间日期与时间。'); return; }
    const tdb = utcToTdb(ms);
    if (manifest && (tdb < manifest.startTdb || tdb > manifest.endTdb)) { setError('日期超出内置历表范围，请选择 2026—2027 年的时间。'); return; }
    void seek(tdb);
  }
  const progress = manifest && frame ? (frame.time-manifest.startTdb)/(manifest.endTdb-manifest.startTdb)*100 : 0;
  const isRegionView = !satelliteView && regionViews.includes(options.view);
  const isSpatial = (isRegionView || satelliteView) && options.presentation !== 'physical';
  const renderOptions = isSpatial ? { ...options, scale: false } : options;
  const earthOffset = BODY_IDS.indexOf('earth') * 3;
  const moonOffset = BODY_IDS.indexOf('moon') * 3;
  const earthMoonDistance = frame ? Math.hypot(...[0, 1, 2].map(axis => frame.positions[moonOffset + axis] - frame.positions[earthOffset + axis])) : null;
  const viewName = satelliteView ? selectedSatelliteId ? `${systemSatellites.find(body => body.id === selectedSatelliteId)?.name ?? '卫星'}近景` : `${bodyById[satelliteParent].name}的卫星系统` : options.view === 'follow' ? `${bodyById[selectedId].name}近景` : views.find(v => v.id === options.view)?.label;
  const earthControls: EarthLayerControls | undefined = !satelliteView && (selectedId === 'earth' || options.view === 'earth-moon') ? { clouds: options.earthClouds !== false, atmosphere: options.earthAtmosphere !== false, onClouds: () => setOptions(o => ({ ...o, earthClouds: !(o.earthClouds ?? true) })), onAtmosphere: () => setOptions(o => ({ ...o, earthAtmosphere: !(o.earthAtmosphere ?? true) })), onObserve: observeEarthAtmosphere } : undefined;
  return <main className={`app-shell ${catalogOpen ? 'sidebar-open' : ''} ${inspectorOpen ? 'inspector-open' : ''} ${immersive ? 'immersive' : ''} ${showRoadmap ? 'roadmap-open' : ''}`}>
    <header className="app-header"><div className="brand"><i className="brand-mark" aria-hidden="true"/><div><div className="brand-name">ORBIT</div><div className="brand-subtitle">太阳系观测站</div></div></div><nav className="header-tabs" aria-label="主要功能"><button className={`header-tab ${mode === 'ephemeris' && !guideTab && !showRoadmap ? 'active' : ''}`} onClick={() => chooseMode('ephemeris')}><Orbit size={16}/>真实太阳系</button><button className={`header-tab ${mode === 'physics' && !guideTab && !showRoadmap ? 'active' : ''}`} onClick={() => chooseMode('physics')}><Activity size={15}/>物理验证</button><button className={`header-tab ${guideTab ? 'active' : ''}`} onClick={() => openGuide('atlas')}><BookOpen size={15}/><span><span className="atlas-nav-prefix">太阳系</span>图鉴</span></button><button className={`header-tab ${showRoadmap ? 'active' : ''}`} onClick={openRoadmap} aria-current={showRoadmap ? 'page' : undefined}><Route size={15}/>扩展路线</button></nav><div className="header-right"><span className="data-status"><i className={`status-dot ${loading ? 'amber' : ''}`}/>{loading || (satelliteView && satelliteData.loading) ? 'LOADING EPHEMERIS' : satelliteView ? 'JPL / NAIF · 2026—2027' : 'JPL HORIZONS · 2026—2027'}</span><button className={`header-immersive icon-button ${immersive ? 'active' : ''}`} onClick={() => { setImmersive(!immersive); setCatalogOpen(false); setInspectorOpen(false); }} aria-pressed={immersive} title={immersive ? '退出沉浸观察' : '沉浸观察：收起侧栏'} aria-label={immersive ? '退出沉浸观察' : '沉浸观察'}><Maximize2 size={16}/><span>{immersive ? '退出沉浸' : '沉浸观察'}</span></button><button className="header-help icon-button" onClick={() => { setShowRoadmap(false); setShowHelp(true); }} aria-label="使用说明"><CircleHelp size={16}/><span>观测指南</span></button></div></header>
    <div className="compact-nav"><button onClick={() => { setCatalogOpen(!catalogOpen); setInspectorOpen(false); }} aria-expanded={catalogOpen}><Layers3 size={14}/>{catalogOpen ? '关闭目录' : '天体目录'}</button><span>太阳 · 行星 · 主要卫星</span><button onClick={() => { setInspectorOpen(!inspectorOpen); setCatalogOpen(false); }} aria-expanded={inspectorOpen}><Info size={14}/>{inspectorOpen ? '关闭参数' : '天体参数'}</button></div><div className="observatory-body">{(catalogOpen || inspectorOpen) && <button className="panel-scrim" aria-label="关闭侧边面板" onClick={() => { setCatalogOpen(false); setInspectorOpen(false); }}/>}<aside className="body-sidebar" aria-label="天体目录"><div className="sidebar-heading"><h2>动态天体</h2><span className="count">已接入 {OBSERVATION_COUNTS.dynamic}</span></div><div className="body-list">{BODIES.map((body, i) => <div key={body.id}>{i === 0 && <div className="sidebar-group">CENTRAL STAR / 中心恒星</div>}{i === 1 && <div className="sidebar-group">TERRESTRIAL / 内太阳系</div>}{body.id === 'jupiter' && <div className="sidebar-group">GIANTS / 外太阳系</div>}<button className={`body-button ${selectedId === body.id ? 'selected' : ''}`} onClick={() => inspectBody(body.id)} aria-pressed={selectedId === body.id}><Orb body={body}/><span className="body-names"><strong>{body.name}</strong><small>{body.englishName}</small></span><span className="body-index">{selectedId === body.id ? <Crosshair size={12}/> : String(i+1).padStart(2, '0')}</span></button>{body.id === 'earth' && <button className="earth-moon-directory-button" onClick={watchEarthMoon}><Orbit size={11}/>地月系统 · 观看月球公转<ChevronRight size={11}/></button>}{satelliteParents.includes(body.id) && <SatelliteChildren parentId={body.id} satellites={SATELLITES.filter(s => s.parentId === body.id)} expanded={satelliteView && satelliteParent === body.id} selectedId={selectedSatelliteId} onOverview={() => openSatelliteSystem(body.id)} onSelect={id => openSatelliteSystem(body.id, id)}/>}</div>)}</div><button className="more-bodies-button" onClick={() => openGuide('atlas')}><BookOpen size={14}/><span>发现更多太阳系成员<small>矮行星 · 卫星 · 小天体</small></span><ArrowUpRight size={12}/></button><div className="sidebar-footer"><div className="eyebrow"><ScanLine size={11}/> BUILT ON REAL OBSERVATIONS</div><p>从我们所在的世界出发，<br/>理解这片浩瀚的宇宙。</p><a className="source-link" href="https://science.nasa.gov/solar-system/solar-system-facts/" target="_blank" rel="noreferrer">探索 NASA 太阳系资料<ArrowUpRight size={11}/></a></div></aside>
    <section className="scene-area" aria-label="三维太阳系场景">{satelliteView ? frame && <SatelliteSystem parentId={satelliteParent} frame={frame} satellites={satelliteData.states} selectedId={selectedSatelliteId} onSelect={setSelectedSatelliteId} physicalScale={options.presentation === 'physical'} trajectories={options.trajectories}/> : <SolarSystem frame={frame} mode={mode} selectedId={selectedId} options={renderOptions} satellites={overviewSatelliteData.states} onSelectSatellite={id => { const satellite = satelliteById[id]; if (satellite) openSatelliteSystem(satellite.parentId, id, false); }} onExploreRegion={region => openGuide('atlas', region === 'kuiper' ? 'pluto' : 'ceres')} onSelect={setSelectedId} onReady={() => setCanvasReady(true)} onCameraInteraction={stopCameraOrbit}/>}<div className="scene-top"><div className="scene-heading"><div className="eyebrow">OUR COSMIC NEIGHBORHOOD</div><div className="scene-title-row"><h1>{viewName}</h1>{!satelliteView && options.view === 'follow' && <div className="body-stepper"><button onClick={() => stepBody(-1)} aria-label="上一个天体" title="上一个天体"><ChevronLeft size={15}/></button><span>{String(BODY_IDS.indexOf(selectedId)+1).padStart(2,'0')} / 10</span><button onClick={() => stepBody(1)} aria-label="下一个天体" title="下一个天体"><ChevronRight size={15}/></button></div>}</div><p className="scene-description">{satelliteView ? '围绕' + bodyById[satelliteParent].name + '公转' : options.view === 'comparison' ? '真实直径比例' : mode === 'ephemeris' ? '真实历表' : '物理推演'} <span> · </span> {satelliteView ? 'NASA / JPL 卫星历表' : options.view === 'comparison' ? '排列与照明为对比示意' : isSpatial ? '距离压缩 · 展示补光' : isRegionView ? '真实距离与大小' : '球体近景 · 独立取景'}</p></div><div className="scene-actions"><button className="outlined-button guide-scene-button" onClick={() => openGuide('tours')} title="打开观察导览"><Compass size={13}/>观察导览</button>{mode === 'physics' && <button className="outlined-button" onClick={() => setShowReport(true)} title="打开验证报告"><TrendingUp size={13}/>验证报告</button>}</div></div><nav className="view-switcher" aria-label="镜头视图">{views.map(view => <button key={view.id} className={!satelliteView && options.view === view.id ? 'active' : ''} onClick={() => chooseView(view.id)}>{view.id === 'overview' && <Globe2 size={11}/>} {view.label}</button>)}<button className={!satelliteView && options.view === 'follow' ? 'active' : ''} onClick={() => chooseView('follow')}><Crosshair size={11}/>天体近景</button><button className={satelliteView ? 'active' : ''} onClick={() => openSatelliteSystem(satelliteParents.includes(selectedId) ? selectedId : satelliteParent)}><Orbit size={11}/>行星卫星</button></nav>
    {satelliteView && <div className="satellite-toolbar"><label className="satellite-parent-select"><span className="sr-only">选择卫星母星</span><select aria-label="选择卫星母星" value={satelliteParent} onChange={e => { if (e.target.value === 'earth') chooseView('earth-moon'); else openSatelliteSystem(e.target.value as BodyId, null, false); }}>{satelliteParents.map(parent => <option key={parent} value={parent}>{bodyById[parent].name}系统</option>)}<option value="earth">地月系统</option></select><ChevronDown size={11}/></label>{selectedSatelliteId ? <button className="satellite-overview-button" onClick={() => setSelectedSatelliteId(null)}><Orbit size={12}/>返回系统全景</button> : <div className="presentation-toggle" role="group" aria-label="卫星系统展示比例"><button className={isSpatial ? 'active' : ''} aria-pressed={isSpatial} onClick={() => setOptions(o => ({ ...o, presentation: 'spatial' }))}>空间观测</button><button className={!isSpatial ? 'active' : ''} aria-pressed={!isSpatial} onClick={() => setOptions(o => ({ ...o, presentation: 'physical' }))}>真实比例</button></div>}<button className="satellite-play-button" onClick={playSatelliteOrbits}><Play size={11}/><span>观看公转<small>{satelliteSpeed(satelliteParent) === 3600 ? '1 小时 / 秒' : '6 小时 / 秒'}</small></span></button><button className={`icon-button satellite-trails-button ${options.trajectories ? 'active' : ''}`} onClick={() => toggleOption('trajectories')} aria-label="卫星轨迹" title="显示或隐藏卫星轨迹" aria-pressed={options.trajectories}><Orbit size={14}/></button></div>}
    {isRegionView && <div className="presentation-controls"><div className={`presentation-main-row ${isSpatial ? 'camera-options-row' : ''}`}><div className="presentation-toggle" role="group" aria-label="空间展示比例"><button className={isSpatial ? 'active' : ''} aria-pressed={isSpatial} onClick={() => setOptions(o => ({ ...o, presentation: 'spatial', exaggerated: false }))}>空间观测</button><button className={!isSpatial ? 'active' : ''} aria-pressed={!isSpatial} onClick={() => setOptions(o => ({ ...o, presentation: 'physical', exaggerated: false }))}>真实比例</button></div>{isSpatial && options.view !== 'earth-moon' && <div className="camera-view-controls" role="group" aria-label="观察视角"><label className="camera-angle-select"><span className="sr-only">观察视角</span><select aria-label="观察视角" value={options.cameraAngle ?? 'perspective'} onChange={event => setOptions(o => ({ ...o, cameraAngle: event.target.value as ViewOptions['cameraAngle'] }))} title="只改变观察镜头，不改变天体状态"><option value="perspective">三维透视</option><option value="top">俯视轨道</option></select><ChevronDown size={10}/></label><button className={`camera-orbit-button ${options.cameraAngle !== 'top' && options.cameraOrbit !== false ? 'active' : ''}`} disabled={options.cameraAngle === 'top'} aria-pressed={options.cameraAngle !== 'top' && options.cameraOrbit !== false} onClick={() => setOptions(o => ({ ...o, cameraOrbit: !(o.cameraOrbit ?? true) }))} title={options.cameraAngle === 'top' ? '自动环绕适用于三维透视' : '缓慢环绕镜头；拖动或缩放后停止，不改变天体运动'}><Orbit size={12}/><span>自动环绕</span><i/></button></div>}{options.view === 'overview' && <button className="overview-earth-action" aria-label="观察地球的云与大气" title="观察地球的云与大气" onClick={() => { observeEarthAtmosphere(); setOptions(o => ({ ...o, earthClouds: true })); }}><Cloud size={12}/><span>地球的云与大气</span><ArrowUpRight size={11}/></button>}{options.view === 'earth-moon' && <div className="earth-moon-readout"><span>{mode === 'ephemeris' ? '真实地月距离' : '推演地月距离'} <strong>{earthMoonDistance === null ? '—' : formatNumber(earthMoonDistance, 0)} km</strong></span><span>半径 · 地:月 <strong>{formatNumber(bodyById.earth.radiusKm / bodyById.moon.radiusKm, 2)}:1</strong></span></div>}</div></div>}
    {!satelliteView && options.view === 'comparison' && <div className="comparison-controls"><div className="comparison-set-buttons" aria-label="大小对比天体范围">{([{ id: 'rocky', label: '岩质天体' }, { id: 'planets', label: '行星与月球' }, { id: 'all', label: '包含太阳' }] as const).map(item => <button key={item.id} className={(options.comparisonSet ?? 'planets') === item.id ? 'active' : ''} aria-pressed={(options.comparisonSet ?? 'planets') === item.id} onClick={() => chooseComparisonSet(item.id)}>{item.label}</button>)}</div><div className="comparison-reading"><span className="comparison-full">{bodyById[selectedId].name}直径 <strong>{formatNumber(bodyById[selectedId].radiusKm * 2, 0)} km</strong><span> · 地球 ×{formatNumber(bodyById[selectedId].radiusKm / bodyById.earth.radiusKm, 2)}</span></span><span className="comparison-compact" title="以地球直径为 1 的比例">{bodyById[selectedId].name} · 地球 ×{formatNumber(bodyById[selectedId].radiusKm / bodyById.earth.radiusKm, 2)}</span></div></div>}
    {mode === 'physics' && <div className={`physics-badge ${options.view === 'comparison' ? 'comparison-physics-badge' : isRegionView ? 'region-physics-badge' : ''}`}><strong>物理推演 · 固定步长 300 s</strong><br/>{physicsEpoch !== null && frame ? `已推进 ${formatNumber((frame.time - physicsEpoch) / 86400, 2)} 天 · 行星系统质心模型` : '正在初始化真实状态…'}<br/>{speed === 1 ? `距下一步还需积累 ${Math.max(0, 300 - pendingSeconds).toFixed(0)} 秒` : `实际推进约 ${formatNumber(actualSpeed, 0)} 倍 · 计算不足时自动降速`}</div>}
    {!satelliteView && <div className="view-controls" role="group" aria-label="显示图层">{([{ key: 'trajectories', label: '轨迹', icon: Orbit }, { key: 'referencePlane', label: '黄道参考平面', icon: Grid3X3 }, { key: 'velocityVectors', label: '速度箭头', icon: TrendingUp }, { key: 'belts', label: '小行星带 / 柯伊伯带示意', icon: Layers3 }, { key: 'scale', label: '距离标尺', icon: Ruler }] as const).map(({ key, label, icon: Icon }) => <button key={key} className={`icon-button ${options[key] && !(key === 'scale' && isSpatial) ? 'active' : ''}`} onClick={() => toggleOption(key)} aria-label={label} title={key === 'scale' && isSpatial ? '距离已压缩，请切换真实比例查看距离标尺' : label} disabled={key === 'scale' && isSpatial} aria-pressed={options[key] && !(key === 'scale' && isSpatial)}><Icon size={16}/></button>)}</div>}
    {(loading || (satelliteView ? satelliteData.loading : !canvasReady && !error)) && <div className="scene-loading"><LoaderCircle size={23} className="spin"/><span>{satelliteView ? '正在读取母星与卫星的真实历表' : loading ? '正在读取真实太阳系历表' : '正在构建观测场景'}</span><p>{satelliteView ? '同步所选时刻的卫星相对位置与速度。' : '下载对应月份的 JPL 几何状态数据。'}<br/>准备完成后即可开始探索。</p></div>}
    {error && <div className="scene-error" role="alert"><Info size={16}/><span>{error}</span><button onClick={() => { setError(''); if (!frame) goNow(); }}> {frame ? '关闭' : '重试'} </button></div>}
    {satelliteView && satelliteData.error && <div className="scene-error" role="alert"><Info size={16}/><span>卫星历表无法载入：{satelliteData.error}</span><button onClick={satelliteData.retry}>重试</button></div>}
    {!satelliteView && options.view === 'overview' && !showReport && <OverviewMembers physics={mode === 'physics'} loadedCount={(frame ? 10 : 0) + overviewSatelliteData.states.length} loading={overviewSatelliteData.loading} error={overviewSatelliteData.error} onRetry={overviewSatelliteData.retry} onSun={() => inspectBody('sun')} onPlanets={() => { chooseComparisonSet('planets'); chooseView('comparison'); }} onEarthMoon={watchEarthMoon} onSatelliteSystem={parent => openSatelliteSystem(parent)} onAtlas={() => openGuide('atlas')} onRoadmap={openRoadmap}/>}
    {showReport && <ValidationPanel selectedId={selectedId} onClose={() => setShowReport(false)}/>}
    </section>{satelliteView ? <SatelliteInspector key={satelliteParent + (selectedSatelliteId ?? "system")} parentId={satelliteParent} satellites={systemSatellites} selectedId={selectedSatelliteId} selectedState={satelliteData.states.find(body => body.id === selectedSatelliteId)} loading={satelliteData.loading} onSelect={setSelectedSatelliteId} onOverview={() => setSelectedSatelliteId(null)} onPlay={playSatelliteOrbits}/> : <Inspector key={selectedId} selectedId={selectedId} frame={frame} mode={mode} onFollow={() => chooseView('follow')} earthControls={earthControls} onSystem={satelliteParents.includes(selectedId) || selectedId === 'earth' || selectedId === 'moon' ? openRelatedSystem : undefined}/>}{guideTab && <ExplorationGuide key={guideTab + guideBodyId} initialTab={guideTab} initialBodyId={guideBodyId} onClose={() => setGuideTab(null)} onObserve={observeTour} onOpenSatellite={parent => openSatelliteSystem(parent)}/>} {showRoadmap && <ExpansionRoadmap onClose={closeRoadmap} onExplore={exploreFromRoadmap} onValidation={validationFromRoadmap}/>}</div>
    <footer className="time-dock"><div className="timeline-row"><span className="timeline-label">TIMELINE</span><div className="timeline-track"><span className="timeline-label">2026.01</span><input type="range" aria-label="太阳系观测时间轴" min={manifest?.startTdb ?? 0} max={manifest?.endTdb ?? 1} step={3600} value={frame?.time ?? 0} disabled={!manifest || loading} style={{ '--progress': `${progress}%` } as CSSProperties} onChange={e => { setPlaying(false); void seek(Number(e.target.value)); }}/><span className="timeline-label">2027.12</span></div></div><div className="time-control-row"><div className="clock-block"><div className="clock-caption">观测时间 · 北京时间 UTC+8</div><div className="clock-time"><CalendarDays size={13}/><input type="datetime-local" step="1" aria-label="观测日期和时间，北京时间" ref={dateInput} defaultValue="" min={manifest ? beijingInput(manifest.startTdb) : '2026-01-01T08:00'} max={manifest ? beijingInput(manifest.endTdb) : '2028-01-01T07:59:59'} disabled={!frame || loading} onFocus={() => { setEditingDate(true); dateCommitted.current = false; }} onChange={() => { dateCommitted.current = false; }} onBlur={e => commitDate(e.currentTarget.value)} onKeyDown={e => { if (e.key === 'Enter') { commitDate(e.currentTarget.value); e.currentTarget.blur(); } if (e.key === 'Escape') { dateCommitted.current = true; setEditingDate(false); e.currentTarget.blur(); } }}/></div></div><div className="time-playback"><button className="icon-button" onClick={reset} title={mode === 'physics' ? '重置至物理推演起点' : '重置到当前时间'} aria-label="重置模拟"><RotateCcw size={16}/></button><button className="play-button" onClick={() => setPlaying(p => !p)} disabled={!frame || loading} title="播放 / 暂停（空格）" aria-label={playing ? '暂停' : '播放'}>{playing ? <Pause size={15} fill="currentColor"/> : <Play size={15} fill="currentColor"/>}</button><div className="speed-control" aria-label="时间倍率">{speeds.map(item => <button key={item.value} className={speed === item.value ? 'active' : ''} onClick={() => setSpeed(item.value)} title={`${item.value.toLocaleString()} 倍时间`} aria-pressed={speed === item.value}>{item.label}</button>)}</div><button className="now-button" onClick={goNow} disabled={loading}><Circle size={9}/>现在</button></div><div className="dock-status"><strong>{mode === 'ephemeris' ? 'JPL 权威历表 · 几何状态' : 'Velocity Verlet · Δt = 300 s'}</strong><br/><span className="green">{loading ? '数据加载中' : playing ? '时间推进中' : '观测已暂停'}</span> · {satelliteView ? selectedSatelliteId ? '卫星近景 · 相对母星历表' : isSpatial ? '卫星系统 · 距离压缩展示' : '卫星系统 · 真实比例' : options.view === 'comparison' ? '直径比例真实 · 排列示意' : isSpatial ? '空间观测 · 距离已压缩' : isRegionView ? '真实距离与大小' : '近景 · 独立取景'}</div></div></footer>
    {showHelp && <div className="help-overlay" role="dialog" aria-modal="true" aria-label="观测指南" onClick={() => setShowHelp(false)}><div className="help-dialog" onClick={e => e.stopPropagation()}><div className="help-title"><h2>从一颗行星，认识太阳系。</h2><button className="icon-button" onClick={() => setShowHelp(false)} title="关闭指南"><X size={18}/></button></div><p>默认从太阳系全景开始，汇总本观测站已接入的 {OBSERVATION_COUNTS.dynamic} 个动态天体。左下角「已接入天体」提供卫星家族入口；另外 {OBSERVATION_COUNTS.knowledgeOnly} 个资料天体可在图鉴查阅。左侧选择天体进入近景，拖动旋转，滚轮缩放。</p><h3>空间观测与真实比例</h3><p>区域视图默认采用「空间观测」：压缩轨道距离并加入展示补光，让球体与轨道在三维空间中清楚可见；真实方位、倾角与运行节奏保持不变。可切换三维透视与俯视轨道，自动环绕只移动镜头，拖动或缩放后会停止。全景中的球体尺寸经过展示映射，精确大小比较请使用「大小对比」。</p><p>地月空间观测严格保留地球与月球的半径比，只缩短两者距离。切换「真实比例」可恢复真实大小与距离关系；空间观测不提供全局距离标尺。单体近景会独立调整镜头，画面大小不能直接互相比。</p><h3>地球的云层与大气</h3><p>选择地球或地月系统后，在右侧分别开关云层与大气层。「观察地球大气」进入近景，便于看到球体边缘的蓝色辉光。云层使用静态云图，大气为散射效果示意，均不是实时气象。</p><h3>从观察走向理解</h3><p>「行星卫星」可以观察火星、木星、土星、天王星和海王星的 {SATELLITES.length} 颗选定卫星。选择母星后，点击「观看公转」会调整时间倍率；点击卫星可近看，点击「返回系统全景」同时观察多颗卫星。「太阳系图鉴」中已接入历表的卫星也有直达入口，其余成员仍为知识与外观示意。</p><h3>让时间流动起来</h3><p>底部日期使用北京时间。点击日期可跳转时刻，拖动时间轴浏览两年；使用 <kbd>空格</kbd> 暂停，改变倍率可以看到不同时间尺度的运动。</p><h3>从真实历表到物理实验</h3><p>「真实太阳系」读取 JPL 历表；「物理验证」从当前真实状态开始，以 300 秒步长计算引力。1× 倍率下要等待 5 分钟才能推进一个完整物理步，推荐使用更高倍率观察。验证报告展示独立的长期基准实验。新增卫星是独立的真实历表观测层，不参与十体引力计算；切换物理验证会返回母星近景。</p><p className="help-footer">坐标：ECLIPJ2000 · 距离：km / AU · 计算时间：TDB<br/>1 AU = 149,597,870.7 km · 贴图为说明性资料，不是实时影像。</p></div></div>}
  </main>;
}
